/*
DIT PUBLIC 4ME REST API REQUEST EXAMPLES

Testing Class100OtherAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package xurrent

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	openapiclient "github.com/xurrent/go-xurrent/xurrent"
	"testing"
)

func Test_xurrent_Class100OtherAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test Class100OtherAPIService V1EnumsGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.Class100OtherAPI.V1EnumsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test Class100OtherAPIService V1MeGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.Class100OtherAPI.V1MeGet(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
