/*
DIT PUBLIC 4ME REST API REQUEST EXAMPLES

Testing Class1RequestsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package xurrent

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	openapiclient "github.com/xurrent/go-xurrent/xurrent"
	"testing"
)

func Test_xurrent_Class1RequestsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test Class1RequestsAPIService V1Requests1Cis1Delete", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.Class1RequestsAPI.V1Requests1Cis1Delete(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test Class1RequestsAPIService V1Requests1Cis1Post", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.Class1RequestsAPI.V1Requests1Cis1Post(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test Class1RequestsAPIService V1Requests1Cis460359Post", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.Class1RequestsAPI.V1Requests1Cis460359Post(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test Class1RequestsAPIService V1Requests1CisGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.Class1RequestsAPI.V1Requests1CisGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test Class1RequestsAPIService V1Requests1DissatisfiedPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.Class1RequestsAPI.V1Requests1DissatisfiedPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test Class1RequestsAPIService V1Requests1Get", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.Class1RequestsAPI.V1Requests1Get(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test Class1RequestsAPIService V1Requests1GroupedRequestsGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.Class1RequestsAPI.V1Requests1GroupedRequestsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test Class1RequestsAPIService V1Requests1NotesPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.Class1RequestsAPI.V1Requests1NotesPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test Class1RequestsAPIService V1Requests1Put", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.Class1RequestsAPI.V1Requests1Put(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test Class1RequestsAPIService V1Requests1SatisfiedPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.Class1RequestsAPI.V1Requests1SatisfiedPost(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test Class1RequestsAPIService V1Requests2048741AuditGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.Class1RequestsAPI.V1Requests2048741AuditGet(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test Class1RequestsAPIService V1RequestsAssignedToMeGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.Class1RequestsAPI.V1RequestsAssignedToMeGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test Class1RequestsAPIService V1RequestsAssignedToMyTeamGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.Class1RequestsAPI.V1RequestsAssignedToMyTeamGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test Class1RequestsAPIService V1RequestsCompletedGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.Class1RequestsAPI.V1RequestsCompletedGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test Class1RequestsAPIService V1RequestsGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.Class1RequestsAPI.V1RequestsGet(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test Class1RequestsAPIService V1RequestsOpenGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.Class1RequestsAPI.V1RequestsOpenGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test Class1RequestsAPIService V1RequestsRequestedByOrForMeGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.Class1RequestsAPI.V1RequestsRequestedByOrForMeGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test Class1RequestsAPIService V1RequestsRequestsOfMyOrganizationGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.Class1RequestsAPI.V1RequestsRequestsOfMyOrganizationGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
