/*
Xurrent REST API

Xurrent REST API. Global conventions (injected on collection GETs): pagination (`per_page`, `search_after`, `search_before`), field selection (`fields`), ordering (`sort`), predefined state (`state`), and `X-Xurrent-Language`. Resource-specific filters use additional query parameters per https://developer.xurrent.com/v1/general/filtering/ — use `collection_query.go` helpers or append encoded query pairs when filters are not modeled as named parameters.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xurrent

import (
	"encoding/json"
)

// checks if the GetWorkflowsId200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetWorkflowsId200Response{}

// GetWorkflowsId200Response struct for GetWorkflowsId200Response
type GetWorkflowsId200Response struct {
	Account                         *GetRequestsId200ResponseAccount         `json:"account,omitempty"`
	ActualEffort                    *float32                                 `json:"actual_effort,omitempty"`
	ActualVsPlannedEffortPercentage *float32                                 `json:"actual_vs_planned_effort_percentage,omitempty"`
	Attachments                     []map[string]interface{}                 `json:"attachments,omitempty"`
	Category                        *string                                  `json:"category,omitempty"`
	CompletedAt                     NullableString                           `json:"completed_at,omitempty"`
	CompletionReason                NullableString                           `json:"completion_reason,omitempty"`
	CompletionTargetAt              *string                                  `json:"completion_target_at,omitempty"`
	CreatedAt                       *string                                  `json:"created_at,omitempty"`
	CustomFields                    NullableString                           `json:"custom_fields,omitempty"`
	Id                              *float32                                 `json:"id,omitempty"`
	Impact                          *string                                  `json:"impact,omitempty"`
	Justification                   *string                                  `json:"justification,omitempty"`
	Manager                         *GetRequestsId200ResponseCreatedBy       `json:"manager,omitempty"`
	NodeID                          *string                                  `json:"nodeID,omitempty"`
	PlannedEffort                   *float32                                 `json:"planned_effort,omitempty"`
	PreventRequestCompletion        *bool                                    `json:"prevent_request_completion,omitempty"`
	Project                         NullableString                           `json:"project,omitempty"`
	Release                         NullableString                           `json:"release,omitempty"`
	ResolutionDuration              NullableString                           `json:"resolution_duration,omitempty"`
	Service                         *GetRequestsIdCis200ResponseInnerService `json:"service,omitempty"`
	Source                          *string                                  `json:"source,omitempty"`
	SourceID                        NullableString                           `json:"sourceID,omitempty"`
	StartAt                         *string                                  `json:"start_at,omitempty"`
	Status                          *string                                  `json:"status,omitempty"`
	Subject                         *string                                  `json:"subject,omitempty"`
	Template                        *GetTasksId200ResponseTemplate           `json:"template,omitempty"`
	UpdatedAt                       *string                                  `json:"updated_at,omitempty"`
	WorkflowType                    *string                                  `json:"workflow_type,omitempty"`
}

// NewGetWorkflowsId200Response instantiates a new GetWorkflowsId200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetWorkflowsId200Response() *GetWorkflowsId200Response {
	this := GetWorkflowsId200Response{}
	return &this
}

// NewGetWorkflowsId200ResponseWithDefaults instantiates a new GetWorkflowsId200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetWorkflowsId200ResponseWithDefaults() *GetWorkflowsId200Response {
	this := GetWorkflowsId200Response{}
	return &this
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *GetWorkflowsId200Response) GetAccount() GetRequestsId200ResponseAccount {
	if o == nil || IsNil(o.Account) {
		var ret GetRequestsId200ResponseAccount
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWorkflowsId200Response) GetAccountOk() (*GetRequestsId200ResponseAccount, bool) {
	if o == nil || IsNil(o.Account) {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *GetWorkflowsId200Response) HasAccount() bool {
	if o != nil && !IsNil(o.Account) {
		return true
	}

	return false
}

// SetAccount gets a reference to the given GetRequestsId200ResponseAccount and assigns it to the Account field.
func (o *GetWorkflowsId200Response) SetAccount(v GetRequestsId200ResponseAccount) {
	o.Account = &v
}

// GetActualEffort returns the ActualEffort field value if set, zero value otherwise.
func (o *GetWorkflowsId200Response) GetActualEffort() float32 {
	if o == nil || IsNil(o.ActualEffort) {
		var ret float32
		return ret
	}
	return *o.ActualEffort
}

// GetActualEffortOk returns a tuple with the ActualEffort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWorkflowsId200Response) GetActualEffortOk() (*float32, bool) {
	if o == nil || IsNil(o.ActualEffort) {
		return nil, false
	}
	return o.ActualEffort, true
}

// HasActualEffort returns a boolean if a field has been set.
func (o *GetWorkflowsId200Response) HasActualEffort() bool {
	if o != nil && !IsNil(o.ActualEffort) {
		return true
	}

	return false
}

// SetActualEffort gets a reference to the given float32 and assigns it to the ActualEffort field.
func (o *GetWorkflowsId200Response) SetActualEffort(v float32) {
	o.ActualEffort = &v
}

// GetActualVsPlannedEffortPercentage returns the ActualVsPlannedEffortPercentage field value if set, zero value otherwise.
func (o *GetWorkflowsId200Response) GetActualVsPlannedEffortPercentage() float32 {
	if o == nil || IsNil(o.ActualVsPlannedEffortPercentage) {
		var ret float32
		return ret
	}
	return *o.ActualVsPlannedEffortPercentage
}

// GetActualVsPlannedEffortPercentageOk returns a tuple with the ActualVsPlannedEffortPercentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWorkflowsId200Response) GetActualVsPlannedEffortPercentageOk() (*float32, bool) {
	if o == nil || IsNil(o.ActualVsPlannedEffortPercentage) {
		return nil, false
	}
	return o.ActualVsPlannedEffortPercentage, true
}

// HasActualVsPlannedEffortPercentage returns a boolean if a field has been set.
func (o *GetWorkflowsId200Response) HasActualVsPlannedEffortPercentage() bool {
	if o != nil && !IsNil(o.ActualVsPlannedEffortPercentage) {
		return true
	}

	return false
}

// SetActualVsPlannedEffortPercentage gets a reference to the given float32 and assigns it to the ActualVsPlannedEffortPercentage field.
func (o *GetWorkflowsId200Response) SetActualVsPlannedEffortPercentage(v float32) {
	o.ActualVsPlannedEffortPercentage = &v
}

// GetAttachments returns the Attachments field value if set, zero value otherwise.
func (o *GetWorkflowsId200Response) GetAttachments() []map[string]interface{} {
	if o == nil || IsNil(o.Attachments) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Attachments
}

// GetAttachmentsOk returns a tuple with the Attachments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWorkflowsId200Response) GetAttachmentsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Attachments) {
		return nil, false
	}
	return o.Attachments, true
}

// HasAttachments returns a boolean if a field has been set.
func (o *GetWorkflowsId200Response) HasAttachments() bool {
	if o != nil && !IsNil(o.Attachments) {
		return true
	}

	return false
}

// SetAttachments gets a reference to the given []map[string]interface{} and assigns it to the Attachments field.
func (o *GetWorkflowsId200Response) SetAttachments(v []map[string]interface{}) {
	o.Attachments = v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *GetWorkflowsId200Response) GetCategory() string {
	if o == nil || IsNil(o.Category) {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWorkflowsId200Response) GetCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *GetWorkflowsId200Response) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *GetWorkflowsId200Response) SetCategory(v string) {
	o.Category = &v
}

// GetCompletedAt returns the CompletedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetWorkflowsId200Response) GetCompletedAt() string {
	if o == nil || IsNil(o.CompletedAt.Get()) {
		var ret string
		return ret
	}
	return *o.CompletedAt.Get()
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetWorkflowsId200Response) GetCompletedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompletedAt.Get(), o.CompletedAt.IsSet()
}

// HasCompletedAt returns a boolean if a field has been set.
func (o *GetWorkflowsId200Response) HasCompletedAt() bool {
	if o != nil && o.CompletedAt.IsSet() {
		return true
	}

	return false
}

// SetCompletedAt gets a reference to the given NullableString and assigns it to the CompletedAt field.
func (o *GetWorkflowsId200Response) SetCompletedAt(v string) {
	o.CompletedAt.Set(&v)
}

// SetCompletedAtNil sets the value for CompletedAt to be an explicit nil
func (o *GetWorkflowsId200Response) SetCompletedAtNil() {
	o.CompletedAt.Set(nil)
}

// UnsetCompletedAt ensures that no value is present for CompletedAt, not even an explicit nil
func (o *GetWorkflowsId200Response) UnsetCompletedAt() {
	o.CompletedAt.Unset()
}

// GetCompletionReason returns the CompletionReason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetWorkflowsId200Response) GetCompletionReason() string {
	if o == nil || IsNil(o.CompletionReason.Get()) {
		var ret string
		return ret
	}
	return *o.CompletionReason.Get()
}

// GetCompletionReasonOk returns a tuple with the CompletionReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetWorkflowsId200Response) GetCompletionReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompletionReason.Get(), o.CompletionReason.IsSet()
}

// HasCompletionReason returns a boolean if a field has been set.
func (o *GetWorkflowsId200Response) HasCompletionReason() bool {
	if o != nil && o.CompletionReason.IsSet() {
		return true
	}

	return false
}

// SetCompletionReason gets a reference to the given NullableString and assigns it to the CompletionReason field.
func (o *GetWorkflowsId200Response) SetCompletionReason(v string) {
	o.CompletionReason.Set(&v)
}

// SetCompletionReasonNil sets the value for CompletionReason to be an explicit nil
func (o *GetWorkflowsId200Response) SetCompletionReasonNil() {
	o.CompletionReason.Set(nil)
}

// UnsetCompletionReason ensures that no value is present for CompletionReason, not even an explicit nil
func (o *GetWorkflowsId200Response) UnsetCompletionReason() {
	o.CompletionReason.Unset()
}

// GetCompletionTargetAt returns the CompletionTargetAt field value if set, zero value otherwise.
func (o *GetWorkflowsId200Response) GetCompletionTargetAt() string {
	if o == nil || IsNil(o.CompletionTargetAt) {
		var ret string
		return ret
	}
	return *o.CompletionTargetAt
}

// GetCompletionTargetAtOk returns a tuple with the CompletionTargetAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWorkflowsId200Response) GetCompletionTargetAtOk() (*string, bool) {
	if o == nil || IsNil(o.CompletionTargetAt) {
		return nil, false
	}
	return o.CompletionTargetAt, true
}

// HasCompletionTargetAt returns a boolean if a field has been set.
func (o *GetWorkflowsId200Response) HasCompletionTargetAt() bool {
	if o != nil && !IsNil(o.CompletionTargetAt) {
		return true
	}

	return false
}

// SetCompletionTargetAt gets a reference to the given string and assigns it to the CompletionTargetAt field.
func (o *GetWorkflowsId200Response) SetCompletionTargetAt(v string) {
	o.CompletionTargetAt = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GetWorkflowsId200Response) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWorkflowsId200Response) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GetWorkflowsId200Response) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *GetWorkflowsId200Response) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetWorkflowsId200Response) GetCustomFields() string {
	if o == nil || IsNil(o.CustomFields.Get()) {
		var ret string
		return ret
	}
	return *o.CustomFields.Get()
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetWorkflowsId200Response) GetCustomFieldsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomFields.Get(), o.CustomFields.IsSet()
}

// HasCustomFields returns a boolean if a field has been set.
func (o *GetWorkflowsId200Response) HasCustomFields() bool {
	if o != nil && o.CustomFields.IsSet() {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given NullableString and assigns it to the CustomFields field.
func (o *GetWorkflowsId200Response) SetCustomFields(v string) {
	o.CustomFields.Set(&v)
}

// SetCustomFieldsNil sets the value for CustomFields to be an explicit nil
func (o *GetWorkflowsId200Response) SetCustomFieldsNil() {
	o.CustomFields.Set(nil)
}

// UnsetCustomFields ensures that no value is present for CustomFields, not even an explicit nil
func (o *GetWorkflowsId200Response) UnsetCustomFields() {
	o.CustomFields.Unset()
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetWorkflowsId200Response) GetId() float32 {
	if o == nil || IsNil(o.Id) {
		var ret float32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWorkflowsId200Response) GetIdOk() (*float32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetWorkflowsId200Response) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given float32 and assigns it to the Id field.
func (o *GetWorkflowsId200Response) SetId(v float32) {
	o.Id = &v
}

// GetImpact returns the Impact field value if set, zero value otherwise.
func (o *GetWorkflowsId200Response) GetImpact() string {
	if o == nil || IsNil(o.Impact) {
		var ret string
		return ret
	}
	return *o.Impact
}

// GetImpactOk returns a tuple with the Impact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWorkflowsId200Response) GetImpactOk() (*string, bool) {
	if o == nil || IsNil(o.Impact) {
		return nil, false
	}
	return o.Impact, true
}

// HasImpact returns a boolean if a field has been set.
func (o *GetWorkflowsId200Response) HasImpact() bool {
	if o != nil && !IsNil(o.Impact) {
		return true
	}

	return false
}

// SetImpact gets a reference to the given string and assigns it to the Impact field.
func (o *GetWorkflowsId200Response) SetImpact(v string) {
	o.Impact = &v
}

// GetJustification returns the Justification field value if set, zero value otherwise.
func (o *GetWorkflowsId200Response) GetJustification() string {
	if o == nil || IsNil(o.Justification) {
		var ret string
		return ret
	}
	return *o.Justification
}

// GetJustificationOk returns a tuple with the Justification field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWorkflowsId200Response) GetJustificationOk() (*string, bool) {
	if o == nil || IsNil(o.Justification) {
		return nil, false
	}
	return o.Justification, true
}

// HasJustification returns a boolean if a field has been set.
func (o *GetWorkflowsId200Response) HasJustification() bool {
	if o != nil && !IsNil(o.Justification) {
		return true
	}

	return false
}

// SetJustification gets a reference to the given string and assigns it to the Justification field.
func (o *GetWorkflowsId200Response) SetJustification(v string) {
	o.Justification = &v
}

// GetManager returns the Manager field value if set, zero value otherwise.
func (o *GetWorkflowsId200Response) GetManager() GetRequestsId200ResponseCreatedBy {
	if o == nil || IsNil(o.Manager) {
		var ret GetRequestsId200ResponseCreatedBy
		return ret
	}
	return *o.Manager
}

// GetManagerOk returns a tuple with the Manager field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWorkflowsId200Response) GetManagerOk() (*GetRequestsId200ResponseCreatedBy, bool) {
	if o == nil || IsNil(o.Manager) {
		return nil, false
	}
	return o.Manager, true
}

// HasManager returns a boolean if a field has been set.
func (o *GetWorkflowsId200Response) HasManager() bool {
	if o != nil && !IsNil(o.Manager) {
		return true
	}

	return false
}

// SetManager gets a reference to the given GetRequestsId200ResponseCreatedBy and assigns it to the Manager field.
func (o *GetWorkflowsId200Response) SetManager(v GetRequestsId200ResponseCreatedBy) {
	o.Manager = &v
}

// GetNodeID returns the NodeID field value if set, zero value otherwise.
func (o *GetWorkflowsId200Response) GetNodeID() string {
	if o == nil || IsNil(o.NodeID) {
		var ret string
		return ret
	}
	return *o.NodeID
}

// GetNodeIDOk returns a tuple with the NodeID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWorkflowsId200Response) GetNodeIDOk() (*string, bool) {
	if o == nil || IsNil(o.NodeID) {
		return nil, false
	}
	return o.NodeID, true
}

// HasNodeID returns a boolean if a field has been set.
func (o *GetWorkflowsId200Response) HasNodeID() bool {
	if o != nil && !IsNil(o.NodeID) {
		return true
	}

	return false
}

// SetNodeID gets a reference to the given string and assigns it to the NodeID field.
func (o *GetWorkflowsId200Response) SetNodeID(v string) {
	o.NodeID = &v
}

// GetPlannedEffort returns the PlannedEffort field value if set, zero value otherwise.
func (o *GetWorkflowsId200Response) GetPlannedEffort() float32 {
	if o == nil || IsNil(o.PlannedEffort) {
		var ret float32
		return ret
	}
	return *o.PlannedEffort
}

// GetPlannedEffortOk returns a tuple with the PlannedEffort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWorkflowsId200Response) GetPlannedEffortOk() (*float32, bool) {
	if o == nil || IsNil(o.PlannedEffort) {
		return nil, false
	}
	return o.PlannedEffort, true
}

// HasPlannedEffort returns a boolean if a field has been set.
func (o *GetWorkflowsId200Response) HasPlannedEffort() bool {
	if o != nil && !IsNil(o.PlannedEffort) {
		return true
	}

	return false
}

// SetPlannedEffort gets a reference to the given float32 and assigns it to the PlannedEffort field.
func (o *GetWorkflowsId200Response) SetPlannedEffort(v float32) {
	o.PlannedEffort = &v
}

// GetPreventRequestCompletion returns the PreventRequestCompletion field value if set, zero value otherwise.
func (o *GetWorkflowsId200Response) GetPreventRequestCompletion() bool {
	if o == nil || IsNil(o.PreventRequestCompletion) {
		var ret bool
		return ret
	}
	return *o.PreventRequestCompletion
}

// GetPreventRequestCompletionOk returns a tuple with the PreventRequestCompletion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWorkflowsId200Response) GetPreventRequestCompletionOk() (*bool, bool) {
	if o == nil || IsNil(o.PreventRequestCompletion) {
		return nil, false
	}
	return o.PreventRequestCompletion, true
}

// HasPreventRequestCompletion returns a boolean if a field has been set.
func (o *GetWorkflowsId200Response) HasPreventRequestCompletion() bool {
	if o != nil && !IsNil(o.PreventRequestCompletion) {
		return true
	}

	return false
}

// SetPreventRequestCompletion gets a reference to the given bool and assigns it to the PreventRequestCompletion field.
func (o *GetWorkflowsId200Response) SetPreventRequestCompletion(v bool) {
	o.PreventRequestCompletion = &v
}

// GetProject returns the Project field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetWorkflowsId200Response) GetProject() string {
	if o == nil || IsNil(o.Project.Get()) {
		var ret string
		return ret
	}
	return *o.Project.Get()
}

// GetProjectOk returns a tuple with the Project field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetWorkflowsId200Response) GetProjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Project.Get(), o.Project.IsSet()
}

// HasProject returns a boolean if a field has been set.
func (o *GetWorkflowsId200Response) HasProject() bool {
	if o != nil && o.Project.IsSet() {
		return true
	}

	return false
}

// SetProject gets a reference to the given NullableString and assigns it to the Project field.
func (o *GetWorkflowsId200Response) SetProject(v string) {
	o.Project.Set(&v)
}

// SetProjectNil sets the value for Project to be an explicit nil
func (o *GetWorkflowsId200Response) SetProjectNil() {
	o.Project.Set(nil)
}

// UnsetProject ensures that no value is present for Project, not even an explicit nil
func (o *GetWorkflowsId200Response) UnsetProject() {
	o.Project.Unset()
}

// GetRelease returns the Release field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetWorkflowsId200Response) GetRelease() string {
	if o == nil || IsNil(o.Release.Get()) {
		var ret string
		return ret
	}
	return *o.Release.Get()
}

// GetReleaseOk returns a tuple with the Release field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetWorkflowsId200Response) GetReleaseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Release.Get(), o.Release.IsSet()
}

// HasRelease returns a boolean if a field has been set.
func (o *GetWorkflowsId200Response) HasRelease() bool {
	if o != nil && o.Release.IsSet() {
		return true
	}

	return false
}

// SetRelease gets a reference to the given NullableString and assigns it to the Release field.
func (o *GetWorkflowsId200Response) SetRelease(v string) {
	o.Release.Set(&v)
}

// SetReleaseNil sets the value for Release to be an explicit nil
func (o *GetWorkflowsId200Response) SetReleaseNil() {
	o.Release.Set(nil)
}

// UnsetRelease ensures that no value is present for Release, not even an explicit nil
func (o *GetWorkflowsId200Response) UnsetRelease() {
	o.Release.Unset()
}

// GetResolutionDuration returns the ResolutionDuration field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetWorkflowsId200Response) GetResolutionDuration() string {
	if o == nil || IsNil(o.ResolutionDuration.Get()) {
		var ret string
		return ret
	}
	return *o.ResolutionDuration.Get()
}

// GetResolutionDurationOk returns a tuple with the ResolutionDuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetWorkflowsId200Response) GetResolutionDurationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResolutionDuration.Get(), o.ResolutionDuration.IsSet()
}

// HasResolutionDuration returns a boolean if a field has been set.
func (o *GetWorkflowsId200Response) HasResolutionDuration() bool {
	if o != nil && o.ResolutionDuration.IsSet() {
		return true
	}

	return false
}

// SetResolutionDuration gets a reference to the given NullableString and assigns it to the ResolutionDuration field.
func (o *GetWorkflowsId200Response) SetResolutionDuration(v string) {
	o.ResolutionDuration.Set(&v)
}

// SetResolutionDurationNil sets the value for ResolutionDuration to be an explicit nil
func (o *GetWorkflowsId200Response) SetResolutionDurationNil() {
	o.ResolutionDuration.Set(nil)
}

// UnsetResolutionDuration ensures that no value is present for ResolutionDuration, not even an explicit nil
func (o *GetWorkflowsId200Response) UnsetResolutionDuration() {
	o.ResolutionDuration.Unset()
}

// GetService returns the Service field value if set, zero value otherwise.
func (o *GetWorkflowsId200Response) GetService() GetRequestsIdCis200ResponseInnerService {
	if o == nil || IsNil(o.Service) {
		var ret GetRequestsIdCis200ResponseInnerService
		return ret
	}
	return *o.Service
}

// GetServiceOk returns a tuple with the Service field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWorkflowsId200Response) GetServiceOk() (*GetRequestsIdCis200ResponseInnerService, bool) {
	if o == nil || IsNil(o.Service) {
		return nil, false
	}
	return o.Service, true
}

// HasService returns a boolean if a field has been set.
func (o *GetWorkflowsId200Response) HasService() bool {
	if o != nil && !IsNil(o.Service) {
		return true
	}

	return false
}

// SetService gets a reference to the given GetRequestsIdCis200ResponseInnerService and assigns it to the Service field.
func (o *GetWorkflowsId200Response) SetService(v GetRequestsIdCis200ResponseInnerService) {
	o.Service = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *GetWorkflowsId200Response) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWorkflowsId200Response) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *GetWorkflowsId200Response) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *GetWorkflowsId200Response) SetSource(v string) {
	o.Source = &v
}

// GetSourceID returns the SourceID field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetWorkflowsId200Response) GetSourceID() string {
	if o == nil || IsNil(o.SourceID.Get()) {
		var ret string
		return ret
	}
	return *o.SourceID.Get()
}

// GetSourceIDOk returns a tuple with the SourceID field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetWorkflowsId200Response) GetSourceIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SourceID.Get(), o.SourceID.IsSet()
}

// HasSourceID returns a boolean if a field has been set.
func (o *GetWorkflowsId200Response) HasSourceID() bool {
	if o != nil && o.SourceID.IsSet() {
		return true
	}

	return false
}

// SetSourceID gets a reference to the given NullableString and assigns it to the SourceID field.
func (o *GetWorkflowsId200Response) SetSourceID(v string) {
	o.SourceID.Set(&v)
}

// SetSourceIDNil sets the value for SourceID to be an explicit nil
func (o *GetWorkflowsId200Response) SetSourceIDNil() {
	o.SourceID.Set(nil)
}

// UnsetSourceID ensures that no value is present for SourceID, not even an explicit nil
func (o *GetWorkflowsId200Response) UnsetSourceID() {
	o.SourceID.Unset()
}

// GetStartAt returns the StartAt field value if set, zero value otherwise.
func (o *GetWorkflowsId200Response) GetStartAt() string {
	if o == nil || IsNil(o.StartAt) {
		var ret string
		return ret
	}
	return *o.StartAt
}

// GetStartAtOk returns a tuple with the StartAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWorkflowsId200Response) GetStartAtOk() (*string, bool) {
	if o == nil || IsNil(o.StartAt) {
		return nil, false
	}
	return o.StartAt, true
}

// HasStartAt returns a boolean if a field has been set.
func (o *GetWorkflowsId200Response) HasStartAt() bool {
	if o != nil && !IsNil(o.StartAt) {
		return true
	}

	return false
}

// SetStartAt gets a reference to the given string and assigns it to the StartAt field.
func (o *GetWorkflowsId200Response) SetStartAt(v string) {
	o.StartAt = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetWorkflowsId200Response) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWorkflowsId200Response) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetWorkflowsId200Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetWorkflowsId200Response) SetStatus(v string) {
	o.Status = &v
}

// GetSubject returns the Subject field value if set, zero value otherwise.
func (o *GetWorkflowsId200Response) GetSubject() string {
	if o == nil || IsNil(o.Subject) {
		var ret string
		return ret
	}
	return *o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWorkflowsId200Response) GetSubjectOk() (*string, bool) {
	if o == nil || IsNil(o.Subject) {
		return nil, false
	}
	return o.Subject, true
}

// HasSubject returns a boolean if a field has been set.
func (o *GetWorkflowsId200Response) HasSubject() bool {
	if o != nil && !IsNil(o.Subject) {
		return true
	}

	return false
}

// SetSubject gets a reference to the given string and assigns it to the Subject field.
func (o *GetWorkflowsId200Response) SetSubject(v string) {
	o.Subject = &v
}

// GetTemplate returns the Template field value if set, zero value otherwise.
func (o *GetWorkflowsId200Response) GetTemplate() GetTasksId200ResponseTemplate {
	if o == nil || IsNil(o.Template) {
		var ret GetTasksId200ResponseTemplate
		return ret
	}
	return *o.Template
}

// GetTemplateOk returns a tuple with the Template field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWorkflowsId200Response) GetTemplateOk() (*GetTasksId200ResponseTemplate, bool) {
	if o == nil || IsNil(o.Template) {
		return nil, false
	}
	return o.Template, true
}

// HasTemplate returns a boolean if a field has been set.
func (o *GetWorkflowsId200Response) HasTemplate() bool {
	if o != nil && !IsNil(o.Template) {
		return true
	}

	return false
}

// SetTemplate gets a reference to the given GetTasksId200ResponseTemplate and assigns it to the Template field.
func (o *GetWorkflowsId200Response) SetTemplate(v GetTasksId200ResponseTemplate) {
	o.Template = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *GetWorkflowsId200Response) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWorkflowsId200Response) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *GetWorkflowsId200Response) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *GetWorkflowsId200Response) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetWorkflowType returns the WorkflowType field value if set, zero value otherwise.
func (o *GetWorkflowsId200Response) GetWorkflowType() string {
	if o == nil || IsNil(o.WorkflowType) {
		var ret string
		return ret
	}
	return *o.WorkflowType
}

// GetWorkflowTypeOk returns a tuple with the WorkflowType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWorkflowsId200Response) GetWorkflowTypeOk() (*string, bool) {
	if o == nil || IsNil(o.WorkflowType) {
		return nil, false
	}
	return o.WorkflowType, true
}

// HasWorkflowType returns a boolean if a field has been set.
func (o *GetWorkflowsId200Response) HasWorkflowType() bool {
	if o != nil && !IsNil(o.WorkflowType) {
		return true
	}

	return false
}

// SetWorkflowType gets a reference to the given string and assigns it to the WorkflowType field.
func (o *GetWorkflowsId200Response) SetWorkflowType(v string) {
	o.WorkflowType = &v
}

func (o GetWorkflowsId200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetWorkflowsId200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Account) {
		toSerialize["account"] = o.Account
	}
	if !IsNil(o.ActualEffort) {
		toSerialize["actual_effort"] = o.ActualEffort
	}
	if !IsNil(o.ActualVsPlannedEffortPercentage) {
		toSerialize["actual_vs_planned_effort_percentage"] = o.ActualVsPlannedEffortPercentage
	}
	if !IsNil(o.Attachments) {
		toSerialize["attachments"] = o.Attachments
	}
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	if o.CompletedAt.IsSet() {
		toSerialize["completed_at"] = o.CompletedAt.Get()
	}
	if o.CompletionReason.IsSet() {
		toSerialize["completion_reason"] = o.CompletionReason.Get()
	}
	if !IsNil(o.CompletionTargetAt) {
		toSerialize["completion_target_at"] = o.CompletionTargetAt
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if o.CustomFields.IsSet() {
		toSerialize["custom_fields"] = o.CustomFields.Get()
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Impact) {
		toSerialize["impact"] = o.Impact
	}
	if !IsNil(o.Justification) {
		toSerialize["justification"] = o.Justification
	}
	if !IsNil(o.Manager) {
		toSerialize["manager"] = o.Manager
	}
	if !IsNil(o.NodeID) {
		toSerialize["nodeID"] = o.NodeID
	}
	if !IsNil(o.PlannedEffort) {
		toSerialize["planned_effort"] = o.PlannedEffort
	}
	if !IsNil(o.PreventRequestCompletion) {
		toSerialize["prevent_request_completion"] = o.PreventRequestCompletion
	}
	if o.Project.IsSet() {
		toSerialize["project"] = o.Project.Get()
	}
	if o.Release.IsSet() {
		toSerialize["release"] = o.Release.Get()
	}
	if o.ResolutionDuration.IsSet() {
		toSerialize["resolution_duration"] = o.ResolutionDuration.Get()
	}
	if !IsNil(o.Service) {
		toSerialize["service"] = o.Service
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if o.SourceID.IsSet() {
		toSerialize["sourceID"] = o.SourceID.Get()
	}
	if !IsNil(o.StartAt) {
		toSerialize["start_at"] = o.StartAt
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Subject) {
		toSerialize["subject"] = o.Subject
	}
	if !IsNil(o.Template) {
		toSerialize["template"] = o.Template
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.WorkflowType) {
		toSerialize["workflow_type"] = o.WorkflowType
	}
	return toSerialize, nil
}

type NullableGetWorkflowsId200Response struct {
	value *GetWorkflowsId200Response
	isSet bool
}

func (v NullableGetWorkflowsId200Response) Get() *GetWorkflowsId200Response {
	return v.value
}

func (v *NullableGetWorkflowsId200Response) Set(val *GetWorkflowsId200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetWorkflowsId200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetWorkflowsId200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetWorkflowsId200Response(val *GetWorkflowsId200Response) *NullableGetWorkflowsId200Response {
	return &NullableGetWorkflowsId200Response{value: val, isSet: true}
}

func (v NullableGetWorkflowsId200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetWorkflowsId200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
