/*
Xurrent REST API

Xurrent REST API. Global conventions (injected on collection GETs): pagination (`per_page`, `search_after`, `search_before`), field selection (`fields`), ordering (`sort`), predefined state (`state`), and `X-Xurrent-Language`. Resource-specific filters use additional query parameters per https://developer.xurrent.com/v1/general/filtering/ — use `collection_query.go` helpers or append encoded query pairs when filters are not modeled as named parameters.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xurrent

import (
	"encoding/json"
)

// checks if the GetCustomCollectionElementsId200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCustomCollectionElementsId200Response{}

// GetCustomCollectionElementsId200Response struct for GetCustomCollectionElementsId200Response
type GetCustomCollectionElementsId200Response struct {
	Attachments          []map[string]interface{} `json:"attachments,omitempty"`
	CreatedAt            *string                  `json:"created_at,omitempty"`
	CustomCollection     *string                  `json:"custom_collection,omitempty"`
	CustomFields         NullableString           `json:"custom_fields,omitempty"`
	Description          NullableString           `json:"description,omitempty"`
	Disabled             *bool                    `json:"disabled,omitempty"`
	Id                   *float32                 `json:"id,omitempty"`
	Information          NullableString           `json:"information,omitempty"`
	LocalizedDescription NullableString           `json:"localized_description,omitempty"`
	LocalizedName        *string                  `json:"localized_name,omitempty"`
	Name                 *string                  `json:"name,omitempty"`
	NodeID               *string                  `json:"nodeID,omitempty"`
	PictureUri           NullableString           `json:"picture_uri,omitempty"`
	Reference            *string                  `json:"reference,omitempty"`
	Source               *string                  `json:"source,omitempty"`
	SourceID             NullableString           `json:"sourceID,omitempty"`
	UpdatedAt            *string                  `json:"updated_at,omitempty"`
}

// NewGetCustomCollectionElementsId200Response instantiates a new GetCustomCollectionElementsId200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCustomCollectionElementsId200Response() *GetCustomCollectionElementsId200Response {
	this := GetCustomCollectionElementsId200Response{}
	return &this
}

// NewGetCustomCollectionElementsId200ResponseWithDefaults instantiates a new GetCustomCollectionElementsId200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCustomCollectionElementsId200ResponseWithDefaults() *GetCustomCollectionElementsId200Response {
	this := GetCustomCollectionElementsId200Response{}
	return &this
}

// GetAttachments returns the Attachments field value if set, zero value otherwise.
func (o *GetCustomCollectionElementsId200Response) GetAttachments() []map[string]interface{} {
	if o == nil || IsNil(o.Attachments) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Attachments
}

// GetAttachmentsOk returns a tuple with the Attachments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCustomCollectionElementsId200Response) GetAttachmentsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Attachments) {
		return nil, false
	}
	return o.Attachments, true
}

// HasAttachments returns a boolean if a field has been set.
func (o *GetCustomCollectionElementsId200Response) HasAttachments() bool {
	if o != nil && !IsNil(o.Attachments) {
		return true
	}

	return false
}

// SetAttachments gets a reference to the given []map[string]interface{} and assigns it to the Attachments field.
func (o *GetCustomCollectionElementsId200Response) SetAttachments(v []map[string]interface{}) {
	o.Attachments = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GetCustomCollectionElementsId200Response) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCustomCollectionElementsId200Response) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GetCustomCollectionElementsId200Response) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *GetCustomCollectionElementsId200Response) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetCustomCollection returns the CustomCollection field value if set, zero value otherwise.
func (o *GetCustomCollectionElementsId200Response) GetCustomCollection() string {
	if o == nil || IsNil(o.CustomCollection) {
		var ret string
		return ret
	}
	return *o.CustomCollection
}

// GetCustomCollectionOk returns a tuple with the CustomCollection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCustomCollectionElementsId200Response) GetCustomCollectionOk() (*string, bool) {
	if o == nil || IsNil(o.CustomCollection) {
		return nil, false
	}
	return o.CustomCollection, true
}

// HasCustomCollection returns a boolean if a field has been set.
func (o *GetCustomCollectionElementsId200Response) HasCustomCollection() bool {
	if o != nil && !IsNil(o.CustomCollection) {
		return true
	}

	return false
}

// SetCustomCollection gets a reference to the given string and assigns it to the CustomCollection field.
func (o *GetCustomCollectionElementsId200Response) SetCustomCollection(v string) {
	o.CustomCollection = &v
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetCustomCollectionElementsId200Response) GetCustomFields() string {
	if o == nil || IsNil(o.CustomFields.Get()) {
		var ret string
		return ret
	}
	return *o.CustomFields.Get()
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCustomCollectionElementsId200Response) GetCustomFieldsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomFields.Get(), o.CustomFields.IsSet()
}

// HasCustomFields returns a boolean if a field has been set.
func (o *GetCustomCollectionElementsId200Response) HasCustomFields() bool {
	if o != nil && o.CustomFields.IsSet() {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given NullableString and assigns it to the CustomFields field.
func (o *GetCustomCollectionElementsId200Response) SetCustomFields(v string) {
	o.CustomFields.Set(&v)
}

// SetCustomFieldsNil sets the value for CustomFields to be an explicit nil
func (o *GetCustomCollectionElementsId200Response) SetCustomFieldsNil() {
	o.CustomFields.Set(nil)
}

// UnsetCustomFields ensures that no value is present for CustomFields, not even an explicit nil
func (o *GetCustomCollectionElementsId200Response) UnsetCustomFields() {
	o.CustomFields.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetCustomCollectionElementsId200Response) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCustomCollectionElementsId200Response) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *GetCustomCollectionElementsId200Response) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *GetCustomCollectionElementsId200Response) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *GetCustomCollectionElementsId200Response) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *GetCustomCollectionElementsId200Response) UnsetDescription() {
	o.Description.Unset()
}

// GetDisabled returns the Disabled field value if set, zero value otherwise.
func (o *GetCustomCollectionElementsId200Response) GetDisabled() bool {
	if o == nil || IsNil(o.Disabled) {
		var ret bool
		return ret
	}
	return *o.Disabled
}

// GetDisabledOk returns a tuple with the Disabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCustomCollectionElementsId200Response) GetDisabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Disabled) {
		return nil, false
	}
	return o.Disabled, true
}

// HasDisabled returns a boolean if a field has been set.
func (o *GetCustomCollectionElementsId200Response) HasDisabled() bool {
	if o != nil && !IsNil(o.Disabled) {
		return true
	}

	return false
}

// SetDisabled gets a reference to the given bool and assigns it to the Disabled field.
func (o *GetCustomCollectionElementsId200Response) SetDisabled(v bool) {
	o.Disabled = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetCustomCollectionElementsId200Response) GetId() float32 {
	if o == nil || IsNil(o.Id) {
		var ret float32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCustomCollectionElementsId200Response) GetIdOk() (*float32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetCustomCollectionElementsId200Response) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given float32 and assigns it to the Id field.
func (o *GetCustomCollectionElementsId200Response) SetId(v float32) {
	o.Id = &v
}

// GetInformation returns the Information field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetCustomCollectionElementsId200Response) GetInformation() string {
	if o == nil || IsNil(o.Information.Get()) {
		var ret string
		return ret
	}
	return *o.Information.Get()
}

// GetInformationOk returns a tuple with the Information field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCustomCollectionElementsId200Response) GetInformationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Information.Get(), o.Information.IsSet()
}

// HasInformation returns a boolean if a field has been set.
func (o *GetCustomCollectionElementsId200Response) HasInformation() bool {
	if o != nil && o.Information.IsSet() {
		return true
	}

	return false
}

// SetInformation gets a reference to the given NullableString and assigns it to the Information field.
func (o *GetCustomCollectionElementsId200Response) SetInformation(v string) {
	o.Information.Set(&v)
}

// SetInformationNil sets the value for Information to be an explicit nil
func (o *GetCustomCollectionElementsId200Response) SetInformationNil() {
	o.Information.Set(nil)
}

// UnsetInformation ensures that no value is present for Information, not even an explicit nil
func (o *GetCustomCollectionElementsId200Response) UnsetInformation() {
	o.Information.Unset()
}

// GetLocalizedDescription returns the LocalizedDescription field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetCustomCollectionElementsId200Response) GetLocalizedDescription() string {
	if o == nil || IsNil(o.LocalizedDescription.Get()) {
		var ret string
		return ret
	}
	return *o.LocalizedDescription.Get()
}

// GetLocalizedDescriptionOk returns a tuple with the LocalizedDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCustomCollectionElementsId200Response) GetLocalizedDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LocalizedDescription.Get(), o.LocalizedDescription.IsSet()
}

// HasLocalizedDescription returns a boolean if a field has been set.
func (o *GetCustomCollectionElementsId200Response) HasLocalizedDescription() bool {
	if o != nil && o.LocalizedDescription.IsSet() {
		return true
	}

	return false
}

// SetLocalizedDescription gets a reference to the given NullableString and assigns it to the LocalizedDescription field.
func (o *GetCustomCollectionElementsId200Response) SetLocalizedDescription(v string) {
	o.LocalizedDescription.Set(&v)
}

// SetLocalizedDescriptionNil sets the value for LocalizedDescription to be an explicit nil
func (o *GetCustomCollectionElementsId200Response) SetLocalizedDescriptionNil() {
	o.LocalizedDescription.Set(nil)
}

// UnsetLocalizedDescription ensures that no value is present for LocalizedDescription, not even an explicit nil
func (o *GetCustomCollectionElementsId200Response) UnsetLocalizedDescription() {
	o.LocalizedDescription.Unset()
}

// GetLocalizedName returns the LocalizedName field value if set, zero value otherwise.
func (o *GetCustomCollectionElementsId200Response) GetLocalizedName() string {
	if o == nil || IsNil(o.LocalizedName) {
		var ret string
		return ret
	}
	return *o.LocalizedName
}

// GetLocalizedNameOk returns a tuple with the LocalizedName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCustomCollectionElementsId200Response) GetLocalizedNameOk() (*string, bool) {
	if o == nil || IsNil(o.LocalizedName) {
		return nil, false
	}
	return o.LocalizedName, true
}

// HasLocalizedName returns a boolean if a field has been set.
func (o *GetCustomCollectionElementsId200Response) HasLocalizedName() bool {
	if o != nil && !IsNil(o.LocalizedName) {
		return true
	}

	return false
}

// SetLocalizedName gets a reference to the given string and assigns it to the LocalizedName field.
func (o *GetCustomCollectionElementsId200Response) SetLocalizedName(v string) {
	o.LocalizedName = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetCustomCollectionElementsId200Response) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCustomCollectionElementsId200Response) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetCustomCollectionElementsId200Response) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetCustomCollectionElementsId200Response) SetName(v string) {
	o.Name = &v
}

// GetNodeID returns the NodeID field value if set, zero value otherwise.
func (o *GetCustomCollectionElementsId200Response) GetNodeID() string {
	if o == nil || IsNil(o.NodeID) {
		var ret string
		return ret
	}
	return *o.NodeID
}

// GetNodeIDOk returns a tuple with the NodeID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCustomCollectionElementsId200Response) GetNodeIDOk() (*string, bool) {
	if o == nil || IsNil(o.NodeID) {
		return nil, false
	}
	return o.NodeID, true
}

// HasNodeID returns a boolean if a field has been set.
func (o *GetCustomCollectionElementsId200Response) HasNodeID() bool {
	if o != nil && !IsNil(o.NodeID) {
		return true
	}

	return false
}

// SetNodeID gets a reference to the given string and assigns it to the NodeID field.
func (o *GetCustomCollectionElementsId200Response) SetNodeID(v string) {
	o.NodeID = &v
}

// GetPictureUri returns the PictureUri field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetCustomCollectionElementsId200Response) GetPictureUri() string {
	if o == nil || IsNil(o.PictureUri.Get()) {
		var ret string
		return ret
	}
	return *o.PictureUri.Get()
}

// GetPictureUriOk returns a tuple with the PictureUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCustomCollectionElementsId200Response) GetPictureUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PictureUri.Get(), o.PictureUri.IsSet()
}

// HasPictureUri returns a boolean if a field has been set.
func (o *GetCustomCollectionElementsId200Response) HasPictureUri() bool {
	if o != nil && o.PictureUri.IsSet() {
		return true
	}

	return false
}

// SetPictureUri gets a reference to the given NullableString and assigns it to the PictureUri field.
func (o *GetCustomCollectionElementsId200Response) SetPictureUri(v string) {
	o.PictureUri.Set(&v)
}

// SetPictureUriNil sets the value for PictureUri to be an explicit nil
func (o *GetCustomCollectionElementsId200Response) SetPictureUriNil() {
	o.PictureUri.Set(nil)
}

// UnsetPictureUri ensures that no value is present for PictureUri, not even an explicit nil
func (o *GetCustomCollectionElementsId200Response) UnsetPictureUri() {
	o.PictureUri.Unset()
}

// GetReference returns the Reference field value if set, zero value otherwise.
func (o *GetCustomCollectionElementsId200Response) GetReference() string {
	if o == nil || IsNil(o.Reference) {
		var ret string
		return ret
	}
	return *o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCustomCollectionElementsId200Response) GetReferenceOk() (*string, bool) {
	if o == nil || IsNil(o.Reference) {
		return nil, false
	}
	return o.Reference, true
}

// HasReference returns a boolean if a field has been set.
func (o *GetCustomCollectionElementsId200Response) HasReference() bool {
	if o != nil && !IsNil(o.Reference) {
		return true
	}

	return false
}

// SetReference gets a reference to the given string and assigns it to the Reference field.
func (o *GetCustomCollectionElementsId200Response) SetReference(v string) {
	o.Reference = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *GetCustomCollectionElementsId200Response) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCustomCollectionElementsId200Response) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *GetCustomCollectionElementsId200Response) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *GetCustomCollectionElementsId200Response) SetSource(v string) {
	o.Source = &v
}

// GetSourceID returns the SourceID field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetCustomCollectionElementsId200Response) GetSourceID() string {
	if o == nil || IsNil(o.SourceID.Get()) {
		var ret string
		return ret
	}
	return *o.SourceID.Get()
}

// GetSourceIDOk returns a tuple with the SourceID field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCustomCollectionElementsId200Response) GetSourceIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SourceID.Get(), o.SourceID.IsSet()
}

// HasSourceID returns a boolean if a field has been set.
func (o *GetCustomCollectionElementsId200Response) HasSourceID() bool {
	if o != nil && o.SourceID.IsSet() {
		return true
	}

	return false
}

// SetSourceID gets a reference to the given NullableString and assigns it to the SourceID field.
func (o *GetCustomCollectionElementsId200Response) SetSourceID(v string) {
	o.SourceID.Set(&v)
}

// SetSourceIDNil sets the value for SourceID to be an explicit nil
func (o *GetCustomCollectionElementsId200Response) SetSourceIDNil() {
	o.SourceID.Set(nil)
}

// UnsetSourceID ensures that no value is present for SourceID, not even an explicit nil
func (o *GetCustomCollectionElementsId200Response) UnsetSourceID() {
	o.SourceID.Unset()
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *GetCustomCollectionElementsId200Response) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCustomCollectionElementsId200Response) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *GetCustomCollectionElementsId200Response) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *GetCustomCollectionElementsId200Response) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

func (o GetCustomCollectionElementsId200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCustomCollectionElementsId200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Attachments) {
		toSerialize["attachments"] = o.Attachments
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.CustomCollection) {
		toSerialize["custom_collection"] = o.CustomCollection
	}
	if o.CustomFields.IsSet() {
		toSerialize["custom_fields"] = o.CustomFields.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !IsNil(o.Disabled) {
		toSerialize["disabled"] = o.Disabled
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if o.Information.IsSet() {
		toSerialize["information"] = o.Information.Get()
	}
	if o.LocalizedDescription.IsSet() {
		toSerialize["localized_description"] = o.LocalizedDescription.Get()
	}
	if !IsNil(o.LocalizedName) {
		toSerialize["localized_name"] = o.LocalizedName
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.NodeID) {
		toSerialize["nodeID"] = o.NodeID
	}
	if o.PictureUri.IsSet() {
		toSerialize["picture_uri"] = o.PictureUri.Get()
	}
	if !IsNil(o.Reference) {
		toSerialize["reference"] = o.Reference
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if o.SourceID.IsSet() {
		toSerialize["sourceID"] = o.SourceID.Get()
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableGetCustomCollectionElementsId200Response struct {
	value *GetCustomCollectionElementsId200Response
	isSet bool
}

func (v NullableGetCustomCollectionElementsId200Response) Get() *GetCustomCollectionElementsId200Response {
	return v.value
}

func (v *NullableGetCustomCollectionElementsId200Response) Set(val *GetCustomCollectionElementsId200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCustomCollectionElementsId200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCustomCollectionElementsId200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCustomCollectionElementsId200Response(val *GetCustomCollectionElementsId200Response) *NullableGetCustomCollectionElementsId200Response {
	return &NullableGetCustomCollectionElementsId200Response{value: val, isSet: true}
}

func (v NullableGetCustomCollectionElementsId200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCustomCollectionElementsId200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
