/*
Xurrent REST API

Xurrent REST API. Global conventions (injected on collection GETs): pagination (`per_page`, `search_after`, `search_before`), field selection (`fields`), ordering (`sort`), predefined state (`state`), and `X-Xurrent-Language`. Resource-specific filters use additional query parameters per https://developer.xurrent.com/v1/general/filtering/ — use `collection_query.go` helpers or append encoded query pairs when filters are not modeled as named parameters.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xurrent

import (
	"encoding/json"
)

// checks if the GetRequestsIdNotes200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRequestsIdNotes200ResponseInner{}

// GetRequestsIdNotes200ResponseInner struct for GetRequestsIdNotes200ResponseInner
type GetRequestsIdNotes200ResponseInner struct {
	Account     *GetRequestsId200ResponseAccount   `json:"account,omitempty"`
	Attachments []map[string]interface{}           `json:"attachments,omitempty"`
	CreatedAt   *string                            `json:"created_at,omitempty"`
	Id          *float32                           `json:"id,omitempty"`
	Internal    *bool                              `json:"internal,omitempty"`
	Medium      *string                            `json:"medium,omitempty"`
	NodeID      *string                            `json:"nodeID,omitempty"`
	Person      *GetRequestsId200ResponseCreatedBy `json:"person,omitempty"`
	Text        *string                            `json:"text,omitempty"`
}

// NewGetRequestsIdNotes200ResponseInner instantiates a new GetRequestsIdNotes200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRequestsIdNotes200ResponseInner() *GetRequestsIdNotes200ResponseInner {
	this := GetRequestsIdNotes200ResponseInner{}
	return &this
}

// NewGetRequestsIdNotes200ResponseInnerWithDefaults instantiates a new GetRequestsIdNotes200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRequestsIdNotes200ResponseInnerWithDefaults() *GetRequestsIdNotes200ResponseInner {
	this := GetRequestsIdNotes200ResponseInner{}
	return &this
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *GetRequestsIdNotes200ResponseInner) GetAccount() GetRequestsId200ResponseAccount {
	if o == nil || IsNil(o.Account) {
		var ret GetRequestsId200ResponseAccount
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRequestsIdNotes200ResponseInner) GetAccountOk() (*GetRequestsId200ResponseAccount, bool) {
	if o == nil || IsNil(o.Account) {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *GetRequestsIdNotes200ResponseInner) HasAccount() bool {
	if o != nil && !IsNil(o.Account) {
		return true
	}

	return false
}

// SetAccount gets a reference to the given GetRequestsId200ResponseAccount and assigns it to the Account field.
func (o *GetRequestsIdNotes200ResponseInner) SetAccount(v GetRequestsId200ResponseAccount) {
	o.Account = &v
}

// GetAttachments returns the Attachments field value if set, zero value otherwise.
func (o *GetRequestsIdNotes200ResponseInner) GetAttachments() []map[string]interface{} {
	if o == nil || IsNil(o.Attachments) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Attachments
}

// GetAttachmentsOk returns a tuple with the Attachments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRequestsIdNotes200ResponseInner) GetAttachmentsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Attachments) {
		return nil, false
	}
	return o.Attachments, true
}

// HasAttachments returns a boolean if a field has been set.
func (o *GetRequestsIdNotes200ResponseInner) HasAttachments() bool {
	if o != nil && !IsNil(o.Attachments) {
		return true
	}

	return false
}

// SetAttachments gets a reference to the given []map[string]interface{} and assigns it to the Attachments field.
func (o *GetRequestsIdNotes200ResponseInner) SetAttachments(v []map[string]interface{}) {
	o.Attachments = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GetRequestsIdNotes200ResponseInner) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRequestsIdNotes200ResponseInner) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GetRequestsIdNotes200ResponseInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *GetRequestsIdNotes200ResponseInner) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetRequestsIdNotes200ResponseInner) GetId() float32 {
	if o == nil || IsNil(o.Id) {
		var ret float32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRequestsIdNotes200ResponseInner) GetIdOk() (*float32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetRequestsIdNotes200ResponseInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given float32 and assigns it to the Id field.
func (o *GetRequestsIdNotes200ResponseInner) SetId(v float32) {
	o.Id = &v
}

// GetInternal returns the Internal field value if set, zero value otherwise.
func (o *GetRequestsIdNotes200ResponseInner) GetInternal() bool {
	if o == nil || IsNil(o.Internal) {
		var ret bool
		return ret
	}
	return *o.Internal
}

// GetInternalOk returns a tuple with the Internal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRequestsIdNotes200ResponseInner) GetInternalOk() (*bool, bool) {
	if o == nil || IsNil(o.Internal) {
		return nil, false
	}
	return o.Internal, true
}

// HasInternal returns a boolean if a field has been set.
func (o *GetRequestsIdNotes200ResponseInner) HasInternal() bool {
	if o != nil && !IsNil(o.Internal) {
		return true
	}

	return false
}

// SetInternal gets a reference to the given bool and assigns it to the Internal field.
func (o *GetRequestsIdNotes200ResponseInner) SetInternal(v bool) {
	o.Internal = &v
}

// GetMedium returns the Medium field value if set, zero value otherwise.
func (o *GetRequestsIdNotes200ResponseInner) GetMedium() string {
	if o == nil || IsNil(o.Medium) {
		var ret string
		return ret
	}
	return *o.Medium
}

// GetMediumOk returns a tuple with the Medium field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRequestsIdNotes200ResponseInner) GetMediumOk() (*string, bool) {
	if o == nil || IsNil(o.Medium) {
		return nil, false
	}
	return o.Medium, true
}

// HasMedium returns a boolean if a field has been set.
func (o *GetRequestsIdNotes200ResponseInner) HasMedium() bool {
	if o != nil && !IsNil(o.Medium) {
		return true
	}

	return false
}

// SetMedium gets a reference to the given string and assigns it to the Medium field.
func (o *GetRequestsIdNotes200ResponseInner) SetMedium(v string) {
	o.Medium = &v
}

// GetNodeID returns the NodeID field value if set, zero value otherwise.
func (o *GetRequestsIdNotes200ResponseInner) GetNodeID() string {
	if o == nil || IsNil(o.NodeID) {
		var ret string
		return ret
	}
	return *o.NodeID
}

// GetNodeIDOk returns a tuple with the NodeID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRequestsIdNotes200ResponseInner) GetNodeIDOk() (*string, bool) {
	if o == nil || IsNil(o.NodeID) {
		return nil, false
	}
	return o.NodeID, true
}

// HasNodeID returns a boolean if a field has been set.
func (o *GetRequestsIdNotes200ResponseInner) HasNodeID() bool {
	if o != nil && !IsNil(o.NodeID) {
		return true
	}

	return false
}

// SetNodeID gets a reference to the given string and assigns it to the NodeID field.
func (o *GetRequestsIdNotes200ResponseInner) SetNodeID(v string) {
	o.NodeID = &v
}

// GetPerson returns the Person field value if set, zero value otherwise.
func (o *GetRequestsIdNotes200ResponseInner) GetPerson() GetRequestsId200ResponseCreatedBy {
	if o == nil || IsNil(o.Person) {
		var ret GetRequestsId200ResponseCreatedBy
		return ret
	}
	return *o.Person
}

// GetPersonOk returns a tuple with the Person field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRequestsIdNotes200ResponseInner) GetPersonOk() (*GetRequestsId200ResponseCreatedBy, bool) {
	if o == nil || IsNil(o.Person) {
		return nil, false
	}
	return o.Person, true
}

// HasPerson returns a boolean if a field has been set.
func (o *GetRequestsIdNotes200ResponseInner) HasPerson() bool {
	if o != nil && !IsNil(o.Person) {
		return true
	}

	return false
}

// SetPerson gets a reference to the given GetRequestsId200ResponseCreatedBy and assigns it to the Person field.
func (o *GetRequestsIdNotes200ResponseInner) SetPerson(v GetRequestsId200ResponseCreatedBy) {
	o.Person = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *GetRequestsIdNotes200ResponseInner) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRequestsIdNotes200ResponseInner) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *GetRequestsIdNotes200ResponseInner) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *GetRequestsIdNotes200ResponseInner) SetText(v string) {
	o.Text = &v
}

func (o GetRequestsIdNotes200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRequestsIdNotes200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Account) {
		toSerialize["account"] = o.Account
	}
	if !IsNil(o.Attachments) {
		toSerialize["attachments"] = o.Attachments
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Internal) {
		toSerialize["internal"] = o.Internal
	}
	if !IsNil(o.Medium) {
		toSerialize["medium"] = o.Medium
	}
	if !IsNil(o.NodeID) {
		toSerialize["nodeID"] = o.NodeID
	}
	if !IsNil(o.Person) {
		toSerialize["person"] = o.Person
	}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	return toSerialize, nil
}

type NullableGetRequestsIdNotes200ResponseInner struct {
	value *GetRequestsIdNotes200ResponseInner
	isSet bool
}

func (v NullableGetRequestsIdNotes200ResponseInner) Get() *GetRequestsIdNotes200ResponseInner {
	return v.value
}

func (v *NullableGetRequestsIdNotes200ResponseInner) Set(val *GetRequestsIdNotes200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRequestsIdNotes200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRequestsIdNotes200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRequestsIdNotes200ResponseInner(val *GetRequestsIdNotes200ResponseInner) *NullableGetRequestsIdNotes200ResponseInner {
	return &NullableGetRequestsIdNotes200ResponseInner{value: val, isSet: true}
}

func (v NullableGetRequestsIdNotes200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRequestsIdNotes200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
