/*
Xurrent REST API

Xurrent REST API. Global conventions (injected on collection GETs): pagination (`per_page`, `search_after`, `search_before`), field selection (`fields`), ordering (`sort`), predefined state (`state`), and `X-Xurrent-Language`. Resource-specific filters use additional query parameters per https://developer.xurrent.com/v1/general/filtering/ — use `collection_query.go` helpers or append encoded query pairs when filters are not modeled as named parameters.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xurrent

import (
	"encoding/json"
)

// checks if the GetAccountUsageStatementsId200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAccountUsageStatementsId200Response{}

// GetAccountUsageStatementsId200Response struct for GetAccountUsageStatementsId200Response
type GetAccountUsageStatementsId200Response struct {
	BillableUserIds    []map[string]interface{} `json:"billable_user_ids,omitempty"`
	ConsumedUserMonths *float32                 `json:"consumed_user_months,omitempty"`
	EndDate            *string                  `json:"end_date,omitempty"`
	Id                 *float32                 `json:"id,omitempty"`
	Month              *float32                 `json:"month,omitempty"`
	NodeID             *string                  `json:"nodeID,omitempty"`
	Plan               *string                  `json:"plan,omitempty"`
	StartDate          *string                  `json:"start_date,omitempty"`
	UserMonths         *float32                 `json:"user_months,omitempty"`
	Year               *float32                 `json:"year,omitempty"`
}

// NewGetAccountUsageStatementsId200Response instantiates a new GetAccountUsageStatementsId200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAccountUsageStatementsId200Response() *GetAccountUsageStatementsId200Response {
	this := GetAccountUsageStatementsId200Response{}
	return &this
}

// NewGetAccountUsageStatementsId200ResponseWithDefaults instantiates a new GetAccountUsageStatementsId200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAccountUsageStatementsId200ResponseWithDefaults() *GetAccountUsageStatementsId200Response {
	this := GetAccountUsageStatementsId200Response{}
	return &this
}

// GetBillableUserIds returns the BillableUserIds field value if set, zero value otherwise.
func (o *GetAccountUsageStatementsId200Response) GetBillableUserIds() []map[string]interface{} {
	if o == nil || IsNil(o.BillableUserIds) {
		var ret []map[string]interface{}
		return ret
	}
	return o.BillableUserIds
}

// GetBillableUserIdsOk returns a tuple with the BillableUserIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountUsageStatementsId200Response) GetBillableUserIdsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.BillableUserIds) {
		return nil, false
	}
	return o.BillableUserIds, true
}

// HasBillableUserIds returns a boolean if a field has been set.
func (o *GetAccountUsageStatementsId200Response) HasBillableUserIds() bool {
	if o != nil && !IsNil(o.BillableUserIds) {
		return true
	}

	return false
}

// SetBillableUserIds gets a reference to the given []map[string]interface{} and assigns it to the BillableUserIds field.
func (o *GetAccountUsageStatementsId200Response) SetBillableUserIds(v []map[string]interface{}) {
	o.BillableUserIds = v
}

// GetConsumedUserMonths returns the ConsumedUserMonths field value if set, zero value otherwise.
func (o *GetAccountUsageStatementsId200Response) GetConsumedUserMonths() float32 {
	if o == nil || IsNil(o.ConsumedUserMonths) {
		var ret float32
		return ret
	}
	return *o.ConsumedUserMonths
}

// GetConsumedUserMonthsOk returns a tuple with the ConsumedUserMonths field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountUsageStatementsId200Response) GetConsumedUserMonthsOk() (*float32, bool) {
	if o == nil || IsNil(o.ConsumedUserMonths) {
		return nil, false
	}
	return o.ConsumedUserMonths, true
}

// HasConsumedUserMonths returns a boolean if a field has been set.
func (o *GetAccountUsageStatementsId200Response) HasConsumedUserMonths() bool {
	if o != nil && !IsNil(o.ConsumedUserMonths) {
		return true
	}

	return false
}

// SetConsumedUserMonths gets a reference to the given float32 and assigns it to the ConsumedUserMonths field.
func (o *GetAccountUsageStatementsId200Response) SetConsumedUserMonths(v float32) {
	o.ConsumedUserMonths = &v
}

// GetEndDate returns the EndDate field value if set, zero value otherwise.
func (o *GetAccountUsageStatementsId200Response) GetEndDate() string {
	if o == nil || IsNil(o.EndDate) {
		var ret string
		return ret
	}
	return *o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountUsageStatementsId200Response) GetEndDateOk() (*string, bool) {
	if o == nil || IsNil(o.EndDate) {
		return nil, false
	}
	return o.EndDate, true
}

// HasEndDate returns a boolean if a field has been set.
func (o *GetAccountUsageStatementsId200Response) HasEndDate() bool {
	if o != nil && !IsNil(o.EndDate) {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given string and assigns it to the EndDate field.
func (o *GetAccountUsageStatementsId200Response) SetEndDate(v string) {
	o.EndDate = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetAccountUsageStatementsId200Response) GetId() float32 {
	if o == nil || IsNil(o.Id) {
		var ret float32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountUsageStatementsId200Response) GetIdOk() (*float32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetAccountUsageStatementsId200Response) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given float32 and assigns it to the Id field.
func (o *GetAccountUsageStatementsId200Response) SetId(v float32) {
	o.Id = &v
}

// GetMonth returns the Month field value if set, zero value otherwise.
func (o *GetAccountUsageStatementsId200Response) GetMonth() float32 {
	if o == nil || IsNil(o.Month) {
		var ret float32
		return ret
	}
	return *o.Month
}

// GetMonthOk returns a tuple with the Month field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountUsageStatementsId200Response) GetMonthOk() (*float32, bool) {
	if o == nil || IsNil(o.Month) {
		return nil, false
	}
	return o.Month, true
}

// HasMonth returns a boolean if a field has been set.
func (o *GetAccountUsageStatementsId200Response) HasMonth() bool {
	if o != nil && !IsNil(o.Month) {
		return true
	}

	return false
}

// SetMonth gets a reference to the given float32 and assigns it to the Month field.
func (o *GetAccountUsageStatementsId200Response) SetMonth(v float32) {
	o.Month = &v
}

// GetNodeID returns the NodeID field value if set, zero value otherwise.
func (o *GetAccountUsageStatementsId200Response) GetNodeID() string {
	if o == nil || IsNil(o.NodeID) {
		var ret string
		return ret
	}
	return *o.NodeID
}

// GetNodeIDOk returns a tuple with the NodeID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountUsageStatementsId200Response) GetNodeIDOk() (*string, bool) {
	if o == nil || IsNil(o.NodeID) {
		return nil, false
	}
	return o.NodeID, true
}

// HasNodeID returns a boolean if a field has been set.
func (o *GetAccountUsageStatementsId200Response) HasNodeID() bool {
	if o != nil && !IsNil(o.NodeID) {
		return true
	}

	return false
}

// SetNodeID gets a reference to the given string and assigns it to the NodeID field.
func (o *GetAccountUsageStatementsId200Response) SetNodeID(v string) {
	o.NodeID = &v
}

// GetPlan returns the Plan field value if set, zero value otherwise.
func (o *GetAccountUsageStatementsId200Response) GetPlan() string {
	if o == nil || IsNil(o.Plan) {
		var ret string
		return ret
	}
	return *o.Plan
}

// GetPlanOk returns a tuple with the Plan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountUsageStatementsId200Response) GetPlanOk() (*string, bool) {
	if o == nil || IsNil(o.Plan) {
		return nil, false
	}
	return o.Plan, true
}

// HasPlan returns a boolean if a field has been set.
func (o *GetAccountUsageStatementsId200Response) HasPlan() bool {
	if o != nil && !IsNil(o.Plan) {
		return true
	}

	return false
}

// SetPlan gets a reference to the given string and assigns it to the Plan field.
func (o *GetAccountUsageStatementsId200Response) SetPlan(v string) {
	o.Plan = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *GetAccountUsageStatementsId200Response) GetStartDate() string {
	if o == nil || IsNil(o.StartDate) {
		var ret string
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountUsageStatementsId200Response) GetStartDateOk() (*string, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *GetAccountUsageStatementsId200Response) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given string and assigns it to the StartDate field.
func (o *GetAccountUsageStatementsId200Response) SetStartDate(v string) {
	o.StartDate = &v
}

// GetUserMonths returns the UserMonths field value if set, zero value otherwise.
func (o *GetAccountUsageStatementsId200Response) GetUserMonths() float32 {
	if o == nil || IsNil(o.UserMonths) {
		var ret float32
		return ret
	}
	return *o.UserMonths
}

// GetUserMonthsOk returns a tuple with the UserMonths field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountUsageStatementsId200Response) GetUserMonthsOk() (*float32, bool) {
	if o == nil || IsNil(o.UserMonths) {
		return nil, false
	}
	return o.UserMonths, true
}

// HasUserMonths returns a boolean if a field has been set.
func (o *GetAccountUsageStatementsId200Response) HasUserMonths() bool {
	if o != nil && !IsNil(o.UserMonths) {
		return true
	}

	return false
}

// SetUserMonths gets a reference to the given float32 and assigns it to the UserMonths field.
func (o *GetAccountUsageStatementsId200Response) SetUserMonths(v float32) {
	o.UserMonths = &v
}

// GetYear returns the Year field value if set, zero value otherwise.
func (o *GetAccountUsageStatementsId200Response) GetYear() float32 {
	if o == nil || IsNil(o.Year) {
		var ret float32
		return ret
	}
	return *o.Year
}

// GetYearOk returns a tuple with the Year field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountUsageStatementsId200Response) GetYearOk() (*float32, bool) {
	if o == nil || IsNil(o.Year) {
		return nil, false
	}
	return o.Year, true
}

// HasYear returns a boolean if a field has been set.
func (o *GetAccountUsageStatementsId200Response) HasYear() bool {
	if o != nil && !IsNil(o.Year) {
		return true
	}

	return false
}

// SetYear gets a reference to the given float32 and assigns it to the Year field.
func (o *GetAccountUsageStatementsId200Response) SetYear(v float32) {
	o.Year = &v
}

func (o GetAccountUsageStatementsId200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAccountUsageStatementsId200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BillableUserIds) {
		toSerialize["billable_user_ids"] = o.BillableUserIds
	}
	if !IsNil(o.ConsumedUserMonths) {
		toSerialize["consumed_user_months"] = o.ConsumedUserMonths
	}
	if !IsNil(o.EndDate) {
		toSerialize["end_date"] = o.EndDate
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Month) {
		toSerialize["month"] = o.Month
	}
	if !IsNil(o.NodeID) {
		toSerialize["nodeID"] = o.NodeID
	}
	if !IsNil(o.Plan) {
		toSerialize["plan"] = o.Plan
	}
	if !IsNil(o.StartDate) {
		toSerialize["start_date"] = o.StartDate
	}
	if !IsNil(o.UserMonths) {
		toSerialize["user_months"] = o.UserMonths
	}
	if !IsNil(o.Year) {
		toSerialize["year"] = o.Year
	}
	return toSerialize, nil
}

type NullableGetAccountUsageStatementsId200Response struct {
	value *GetAccountUsageStatementsId200Response
	isSet bool
}

func (v NullableGetAccountUsageStatementsId200Response) Get() *GetAccountUsageStatementsId200Response {
	return v.value
}

func (v *NullableGetAccountUsageStatementsId200Response) Set(val *GetAccountUsageStatementsId200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAccountUsageStatementsId200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAccountUsageStatementsId200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAccountUsageStatementsId200Response(val *GetAccountUsageStatementsId200Response) *NullableGetAccountUsageStatementsId200Response {
	return &NullableGetAccountUsageStatementsId200Response{value: val, isSet: true}
}

func (v NullableGetAccountUsageStatementsId200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAccountUsageStatementsId200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
