/*
Xurrent REST API

Xurrent REST API. Global conventions (injected on collection GETs): pagination (`per_page`, `search_after`, `search_before`), field selection (`fields`), ordering (`sort`), predefined state (`state`), and `X-Xurrent-Language`. Resource-specific filters use additional query parameters per https://developer.xurrent.com/v1/general/filtering/ — use `collection_query.go` helpers or append encoded query pairs when filters are not modeled as named parameters.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xurrent

import (
	"encoding/json"
)

// checks if the GetProducts200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetProducts200ResponseInner{}

// GetProducts200ResponseInner struct for GetProducts200ResponseInner
type GetProducts200ResponseInner struct {
	Category    *string        `json:"category,omitempty"`
	CreatedAt   *string        `json:"created_at,omitempty"`
	Disabled    *bool          `json:"disabled,omitempty"`
	Id          *float32       `json:"id,omitempty"`
	Name        *string        `json:"name,omitempty"`
	NodeID      *string        `json:"nodeID,omitempty"`
	Service     NullableString `json:"service,omitempty"`
	SourceID    NullableString `json:"sourceID,omitempty"`
	SupportTeam NullableString `json:"support_team,omitempty"`
	UpdatedAt   *string        `json:"updated_at,omitempty"`
}

// NewGetProducts200ResponseInner instantiates a new GetProducts200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetProducts200ResponseInner() *GetProducts200ResponseInner {
	this := GetProducts200ResponseInner{}
	return &this
}

// NewGetProducts200ResponseInnerWithDefaults instantiates a new GetProducts200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetProducts200ResponseInnerWithDefaults() *GetProducts200ResponseInner {
	this := GetProducts200ResponseInner{}
	return &this
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *GetProducts200ResponseInner) GetCategory() string {
	if o == nil || IsNil(o.Category) {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProducts200ResponseInner) GetCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *GetProducts200ResponseInner) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *GetProducts200ResponseInner) SetCategory(v string) {
	o.Category = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GetProducts200ResponseInner) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProducts200ResponseInner) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GetProducts200ResponseInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *GetProducts200ResponseInner) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetDisabled returns the Disabled field value if set, zero value otherwise.
func (o *GetProducts200ResponseInner) GetDisabled() bool {
	if o == nil || IsNil(o.Disabled) {
		var ret bool
		return ret
	}
	return *o.Disabled
}

// GetDisabledOk returns a tuple with the Disabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProducts200ResponseInner) GetDisabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Disabled) {
		return nil, false
	}
	return o.Disabled, true
}

// HasDisabled returns a boolean if a field has been set.
func (o *GetProducts200ResponseInner) HasDisabled() bool {
	if o != nil && !IsNil(o.Disabled) {
		return true
	}

	return false
}

// SetDisabled gets a reference to the given bool and assigns it to the Disabled field.
func (o *GetProducts200ResponseInner) SetDisabled(v bool) {
	o.Disabled = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetProducts200ResponseInner) GetId() float32 {
	if o == nil || IsNil(o.Id) {
		var ret float32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProducts200ResponseInner) GetIdOk() (*float32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetProducts200ResponseInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given float32 and assigns it to the Id field.
func (o *GetProducts200ResponseInner) SetId(v float32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetProducts200ResponseInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProducts200ResponseInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetProducts200ResponseInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetProducts200ResponseInner) SetName(v string) {
	o.Name = &v
}

// GetNodeID returns the NodeID field value if set, zero value otherwise.
func (o *GetProducts200ResponseInner) GetNodeID() string {
	if o == nil || IsNil(o.NodeID) {
		var ret string
		return ret
	}
	return *o.NodeID
}

// GetNodeIDOk returns a tuple with the NodeID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProducts200ResponseInner) GetNodeIDOk() (*string, bool) {
	if o == nil || IsNil(o.NodeID) {
		return nil, false
	}
	return o.NodeID, true
}

// HasNodeID returns a boolean if a field has been set.
func (o *GetProducts200ResponseInner) HasNodeID() bool {
	if o != nil && !IsNil(o.NodeID) {
		return true
	}

	return false
}

// SetNodeID gets a reference to the given string and assigns it to the NodeID field.
func (o *GetProducts200ResponseInner) SetNodeID(v string) {
	o.NodeID = &v
}

// GetService returns the Service field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetProducts200ResponseInner) GetService() string {
	if o == nil || IsNil(o.Service.Get()) {
		var ret string
		return ret
	}
	return *o.Service.Get()
}

// GetServiceOk returns a tuple with the Service field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetProducts200ResponseInner) GetServiceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Service.Get(), o.Service.IsSet()
}

// HasService returns a boolean if a field has been set.
func (o *GetProducts200ResponseInner) HasService() bool {
	if o != nil && o.Service.IsSet() {
		return true
	}

	return false
}

// SetService gets a reference to the given NullableString and assigns it to the Service field.
func (o *GetProducts200ResponseInner) SetService(v string) {
	o.Service.Set(&v)
}

// SetServiceNil sets the value for Service to be an explicit nil
func (o *GetProducts200ResponseInner) SetServiceNil() {
	o.Service.Set(nil)
}

// UnsetService ensures that no value is present for Service, not even an explicit nil
func (o *GetProducts200ResponseInner) UnsetService() {
	o.Service.Unset()
}

// GetSourceID returns the SourceID field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetProducts200ResponseInner) GetSourceID() string {
	if o == nil || IsNil(o.SourceID.Get()) {
		var ret string
		return ret
	}
	return *o.SourceID.Get()
}

// GetSourceIDOk returns a tuple with the SourceID field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetProducts200ResponseInner) GetSourceIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SourceID.Get(), o.SourceID.IsSet()
}

// HasSourceID returns a boolean if a field has been set.
func (o *GetProducts200ResponseInner) HasSourceID() bool {
	if o != nil && o.SourceID.IsSet() {
		return true
	}

	return false
}

// SetSourceID gets a reference to the given NullableString and assigns it to the SourceID field.
func (o *GetProducts200ResponseInner) SetSourceID(v string) {
	o.SourceID.Set(&v)
}

// SetSourceIDNil sets the value for SourceID to be an explicit nil
func (o *GetProducts200ResponseInner) SetSourceIDNil() {
	o.SourceID.Set(nil)
}

// UnsetSourceID ensures that no value is present for SourceID, not even an explicit nil
func (o *GetProducts200ResponseInner) UnsetSourceID() {
	o.SourceID.Unset()
}

// GetSupportTeam returns the SupportTeam field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetProducts200ResponseInner) GetSupportTeam() string {
	if o == nil || IsNil(o.SupportTeam.Get()) {
		var ret string
		return ret
	}
	return *o.SupportTeam.Get()
}

// GetSupportTeamOk returns a tuple with the SupportTeam field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetProducts200ResponseInner) GetSupportTeamOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SupportTeam.Get(), o.SupportTeam.IsSet()
}

// HasSupportTeam returns a boolean if a field has been set.
func (o *GetProducts200ResponseInner) HasSupportTeam() bool {
	if o != nil && o.SupportTeam.IsSet() {
		return true
	}

	return false
}

// SetSupportTeam gets a reference to the given NullableString and assigns it to the SupportTeam field.
func (o *GetProducts200ResponseInner) SetSupportTeam(v string) {
	o.SupportTeam.Set(&v)
}

// SetSupportTeamNil sets the value for SupportTeam to be an explicit nil
func (o *GetProducts200ResponseInner) SetSupportTeamNil() {
	o.SupportTeam.Set(nil)
}

// UnsetSupportTeam ensures that no value is present for SupportTeam, not even an explicit nil
func (o *GetProducts200ResponseInner) UnsetSupportTeam() {
	o.SupportTeam.Unset()
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *GetProducts200ResponseInner) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProducts200ResponseInner) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *GetProducts200ResponseInner) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *GetProducts200ResponseInner) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

func (o GetProducts200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetProducts200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Disabled) {
		toSerialize["disabled"] = o.Disabled
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.NodeID) {
		toSerialize["nodeID"] = o.NodeID
	}
	if o.Service.IsSet() {
		toSerialize["service"] = o.Service.Get()
	}
	if o.SourceID.IsSet() {
		toSerialize["sourceID"] = o.SourceID.Get()
	}
	if o.SupportTeam.IsSet() {
		toSerialize["support_team"] = o.SupportTeam.Get()
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableGetProducts200ResponseInner struct {
	value *GetProducts200ResponseInner
	isSet bool
}

func (v NullableGetProducts200ResponseInner) Get() *GetProducts200ResponseInner {
	return v.value
}

func (v *NullableGetProducts200ResponseInner) Set(val *GetProducts200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetProducts200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetProducts200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetProducts200ResponseInner(val *GetProducts200ResponseInner) *NullableGetProducts200ResponseInner {
	return &NullableGetProducts200ResponseInner{value: val, isSet: true}
}

func (v NullableGetProducts200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetProducts200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
