/*
Xurrent REST API

Xurrent REST API. Global conventions (injected on collection GETs): pagination (`per_page`, `search_after`, `search_before`), field selection (`fields`), ordering (`sort`), predefined state (`state`), and `X-Xurrent-Language`. Resource-specific filters use additional query parameters per https://developer.xurrent.com/v1/general/filtering/ — use `collection_query.go` helpers or append encoded query pairs when filters are not modeled as named parameters.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xurrent

import (
	"encoding/json"
)

// checks if the PostPeople201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostPeople201Response{}

// PostPeople201Response struct for PostPeople201Response
type PostPeople201Response struct {
	Account                  *GetRequestsId200ResponseAccount   `json:"account,omitempty"`
	Addresses                []map[string]interface{}           `json:"addresses,omitempty"`
	Attachments              []map[string]interface{}           `json:"attachments,omitempty"`
	AuthenticationID         NullableString                     `json:"authenticationID,omitempty"`
	AutoTranslation          *bool                              `json:"auto_translation,omitempty"`
	ColorMode                *string                            `json:"color_mode,omitempty"`
	Contacts                 []map[string]interface{}           `json:"contacts,omitempty"`
	CostPerHour              NullableString                     `json:"cost_per_hour,omitempty"`
	CostPerHourCurrency      NullableString                     `json:"cost_per_hour_currency,omitempty"`
	CreatedAt                *string                            `json:"created_at,omitempty"`
	CustomFields             NullableString                     `json:"custom_fields,omitempty"`
	Disabled                 *bool                              `json:"disabled,omitempty"`
	DoNotTranslateLanguages  NullableString                     `json:"do_not_translate_languages,omitempty"`
	EmployeeID               NullableString                     `json:"employeeID,omitempty"`
	ExcludeTeamNotifications *bool                              `json:"exclude_team_notifications,omitempty"`
	Formats                  *PostPeople201ResponseFormats      `json:"formats,omitempty"`
	Guest                    *bool                              `json:"guest,omitempty"`
	Id                       *float32                           `json:"id,omitempty"`
	Information              NullableString                     `json:"information,omitempty"`
	JobTitle                 NullableString                     `json:"job_title,omitempty"`
	Locale                   *string                            `json:"locale,omitempty"`
	Location                 NullableString                     `json:"location,omitempty"`
	Manager                  NullableString                     `json:"manager,omitempty"`
	Name                     *string                            `json:"name,omitempty"`
	NodeID                   *string                            `json:"nodeID,omitempty"`
	OauthPersonEnablement    *bool                              `json:"oauth_person_enablement,omitempty"`
	Organization             *GetRequestsId200ResponseCreatedBy `json:"organization,omitempty"`
	PictureUri               NullableString                     `json:"picture_uri,omitempty"`
	PlayPrivateChatSound     *string                            `json:"play_private_chat_sound,omitempty"`
	PlaySupportChatSound     *string                            `json:"play_support_chat_sound,omitempty"`
	PrimaryEmail             *string                            `json:"primary_email,omitempty"`
	SendEmailNotifications   *string                            `json:"send_email_notifications,omitempty"`
	ShowNotificationPopup    *string                            `json:"show_notification_popup,omitempty"`
	ShowPrivateChatPopup     *string                            `json:"show_private_chat_popup,omitempty"`
	ShowSupportChatPopup     *string                            `json:"show_support_chat_popup,omitempty"`
	Site                     NullableString                     `json:"site,omitempty"`
	Source                   *string                            `json:"source,omitempty"`
	SourceID                 NullableString                     `json:"sourceID,omitempty"`
	SupportID                NullableString                     `json:"supportID,omitempty"`
	TimeFormat24h            *bool                              `json:"time_format_24h,omitempty"`
	TimeZone                 *string                            `json:"time_zone,omitempty"`
	UiExtension              NullableString                     `json:"ui_extension,omitempty"`
	UpdatedAt                *string                            `json:"updated_at,omitempty"`
	Vip                      *bool                              `json:"vip,omitempty"`
	WorkHours                NullableString                     `json:"work_hours,omitempty"`
}

// NewPostPeople201Response instantiates a new PostPeople201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostPeople201Response() *PostPeople201Response {
	this := PostPeople201Response{}
	return &this
}

// NewPostPeople201ResponseWithDefaults instantiates a new PostPeople201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostPeople201ResponseWithDefaults() *PostPeople201Response {
	this := PostPeople201Response{}
	return &this
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *PostPeople201Response) GetAccount() GetRequestsId200ResponseAccount {
	if o == nil || IsNil(o.Account) {
		var ret GetRequestsId200ResponseAccount
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostPeople201Response) GetAccountOk() (*GetRequestsId200ResponseAccount, bool) {
	if o == nil || IsNil(o.Account) {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *PostPeople201Response) HasAccount() bool {
	if o != nil && !IsNil(o.Account) {
		return true
	}

	return false
}

// SetAccount gets a reference to the given GetRequestsId200ResponseAccount and assigns it to the Account field.
func (o *PostPeople201Response) SetAccount(v GetRequestsId200ResponseAccount) {
	o.Account = &v
}

// GetAddresses returns the Addresses field value if set, zero value otherwise.
func (o *PostPeople201Response) GetAddresses() []map[string]interface{} {
	if o == nil || IsNil(o.Addresses) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Addresses
}

// GetAddressesOk returns a tuple with the Addresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostPeople201Response) GetAddressesOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Addresses) {
		return nil, false
	}
	return o.Addresses, true
}

// HasAddresses returns a boolean if a field has been set.
func (o *PostPeople201Response) HasAddresses() bool {
	if o != nil && !IsNil(o.Addresses) {
		return true
	}

	return false
}

// SetAddresses gets a reference to the given []map[string]interface{} and assigns it to the Addresses field.
func (o *PostPeople201Response) SetAddresses(v []map[string]interface{}) {
	o.Addresses = v
}

// GetAttachments returns the Attachments field value if set, zero value otherwise.
func (o *PostPeople201Response) GetAttachments() []map[string]interface{} {
	if o == nil || IsNil(o.Attachments) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Attachments
}

// GetAttachmentsOk returns a tuple with the Attachments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostPeople201Response) GetAttachmentsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Attachments) {
		return nil, false
	}
	return o.Attachments, true
}

// HasAttachments returns a boolean if a field has been set.
func (o *PostPeople201Response) HasAttachments() bool {
	if o != nil && !IsNil(o.Attachments) {
		return true
	}

	return false
}

// SetAttachments gets a reference to the given []map[string]interface{} and assigns it to the Attachments field.
func (o *PostPeople201Response) SetAttachments(v []map[string]interface{}) {
	o.Attachments = v
}

// GetAuthenticationID returns the AuthenticationID field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PostPeople201Response) GetAuthenticationID() string {
	if o == nil || IsNil(o.AuthenticationID.Get()) {
		var ret string
		return ret
	}
	return *o.AuthenticationID.Get()
}

// GetAuthenticationIDOk returns a tuple with the AuthenticationID field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PostPeople201Response) GetAuthenticationIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AuthenticationID.Get(), o.AuthenticationID.IsSet()
}

// HasAuthenticationID returns a boolean if a field has been set.
func (o *PostPeople201Response) HasAuthenticationID() bool {
	if o != nil && o.AuthenticationID.IsSet() {
		return true
	}

	return false
}

// SetAuthenticationID gets a reference to the given NullableString and assigns it to the AuthenticationID field.
func (o *PostPeople201Response) SetAuthenticationID(v string) {
	o.AuthenticationID.Set(&v)
}

// SetAuthenticationIDNil sets the value for AuthenticationID to be an explicit nil
func (o *PostPeople201Response) SetAuthenticationIDNil() {
	o.AuthenticationID.Set(nil)
}

// UnsetAuthenticationID ensures that no value is present for AuthenticationID, not even an explicit nil
func (o *PostPeople201Response) UnsetAuthenticationID() {
	o.AuthenticationID.Unset()
}

// GetAutoTranslation returns the AutoTranslation field value if set, zero value otherwise.
func (o *PostPeople201Response) GetAutoTranslation() bool {
	if o == nil || IsNil(o.AutoTranslation) {
		var ret bool
		return ret
	}
	return *o.AutoTranslation
}

// GetAutoTranslationOk returns a tuple with the AutoTranslation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostPeople201Response) GetAutoTranslationOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoTranslation) {
		return nil, false
	}
	return o.AutoTranslation, true
}

// HasAutoTranslation returns a boolean if a field has been set.
func (o *PostPeople201Response) HasAutoTranslation() bool {
	if o != nil && !IsNil(o.AutoTranslation) {
		return true
	}

	return false
}

// SetAutoTranslation gets a reference to the given bool and assigns it to the AutoTranslation field.
func (o *PostPeople201Response) SetAutoTranslation(v bool) {
	o.AutoTranslation = &v
}

// GetColorMode returns the ColorMode field value if set, zero value otherwise.
func (o *PostPeople201Response) GetColorMode() string {
	if o == nil || IsNil(o.ColorMode) {
		var ret string
		return ret
	}
	return *o.ColorMode
}

// GetColorModeOk returns a tuple with the ColorMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostPeople201Response) GetColorModeOk() (*string, bool) {
	if o == nil || IsNil(o.ColorMode) {
		return nil, false
	}
	return o.ColorMode, true
}

// HasColorMode returns a boolean if a field has been set.
func (o *PostPeople201Response) HasColorMode() bool {
	if o != nil && !IsNil(o.ColorMode) {
		return true
	}

	return false
}

// SetColorMode gets a reference to the given string and assigns it to the ColorMode field.
func (o *PostPeople201Response) SetColorMode(v string) {
	o.ColorMode = &v
}

// GetContacts returns the Contacts field value if set, zero value otherwise.
func (o *PostPeople201Response) GetContacts() []map[string]interface{} {
	if o == nil || IsNil(o.Contacts) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Contacts
}

// GetContactsOk returns a tuple with the Contacts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostPeople201Response) GetContactsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Contacts) {
		return nil, false
	}
	return o.Contacts, true
}

// HasContacts returns a boolean if a field has been set.
func (o *PostPeople201Response) HasContacts() bool {
	if o != nil && !IsNil(o.Contacts) {
		return true
	}

	return false
}

// SetContacts gets a reference to the given []map[string]interface{} and assigns it to the Contacts field.
func (o *PostPeople201Response) SetContacts(v []map[string]interface{}) {
	o.Contacts = v
}

// GetCostPerHour returns the CostPerHour field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PostPeople201Response) GetCostPerHour() string {
	if o == nil || IsNil(o.CostPerHour.Get()) {
		var ret string
		return ret
	}
	return *o.CostPerHour.Get()
}

// GetCostPerHourOk returns a tuple with the CostPerHour field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PostPeople201Response) GetCostPerHourOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CostPerHour.Get(), o.CostPerHour.IsSet()
}

// HasCostPerHour returns a boolean if a field has been set.
func (o *PostPeople201Response) HasCostPerHour() bool {
	if o != nil && o.CostPerHour.IsSet() {
		return true
	}

	return false
}

// SetCostPerHour gets a reference to the given NullableString and assigns it to the CostPerHour field.
func (o *PostPeople201Response) SetCostPerHour(v string) {
	o.CostPerHour.Set(&v)
}

// SetCostPerHourNil sets the value for CostPerHour to be an explicit nil
func (o *PostPeople201Response) SetCostPerHourNil() {
	o.CostPerHour.Set(nil)
}

// UnsetCostPerHour ensures that no value is present for CostPerHour, not even an explicit nil
func (o *PostPeople201Response) UnsetCostPerHour() {
	o.CostPerHour.Unset()
}

// GetCostPerHourCurrency returns the CostPerHourCurrency field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PostPeople201Response) GetCostPerHourCurrency() string {
	if o == nil || IsNil(o.CostPerHourCurrency.Get()) {
		var ret string
		return ret
	}
	return *o.CostPerHourCurrency.Get()
}

// GetCostPerHourCurrencyOk returns a tuple with the CostPerHourCurrency field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PostPeople201Response) GetCostPerHourCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CostPerHourCurrency.Get(), o.CostPerHourCurrency.IsSet()
}

// HasCostPerHourCurrency returns a boolean if a field has been set.
func (o *PostPeople201Response) HasCostPerHourCurrency() bool {
	if o != nil && o.CostPerHourCurrency.IsSet() {
		return true
	}

	return false
}

// SetCostPerHourCurrency gets a reference to the given NullableString and assigns it to the CostPerHourCurrency field.
func (o *PostPeople201Response) SetCostPerHourCurrency(v string) {
	o.CostPerHourCurrency.Set(&v)
}

// SetCostPerHourCurrencyNil sets the value for CostPerHourCurrency to be an explicit nil
func (o *PostPeople201Response) SetCostPerHourCurrencyNil() {
	o.CostPerHourCurrency.Set(nil)
}

// UnsetCostPerHourCurrency ensures that no value is present for CostPerHourCurrency, not even an explicit nil
func (o *PostPeople201Response) UnsetCostPerHourCurrency() {
	o.CostPerHourCurrency.Unset()
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *PostPeople201Response) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostPeople201Response) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *PostPeople201Response) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *PostPeople201Response) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PostPeople201Response) GetCustomFields() string {
	if o == nil || IsNil(o.CustomFields.Get()) {
		var ret string
		return ret
	}
	return *o.CustomFields.Get()
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PostPeople201Response) GetCustomFieldsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomFields.Get(), o.CustomFields.IsSet()
}

// HasCustomFields returns a boolean if a field has been set.
func (o *PostPeople201Response) HasCustomFields() bool {
	if o != nil && o.CustomFields.IsSet() {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given NullableString and assigns it to the CustomFields field.
func (o *PostPeople201Response) SetCustomFields(v string) {
	o.CustomFields.Set(&v)
}

// SetCustomFieldsNil sets the value for CustomFields to be an explicit nil
func (o *PostPeople201Response) SetCustomFieldsNil() {
	o.CustomFields.Set(nil)
}

// UnsetCustomFields ensures that no value is present for CustomFields, not even an explicit nil
func (o *PostPeople201Response) UnsetCustomFields() {
	o.CustomFields.Unset()
}

// GetDisabled returns the Disabled field value if set, zero value otherwise.
func (o *PostPeople201Response) GetDisabled() bool {
	if o == nil || IsNil(o.Disabled) {
		var ret bool
		return ret
	}
	return *o.Disabled
}

// GetDisabledOk returns a tuple with the Disabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostPeople201Response) GetDisabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Disabled) {
		return nil, false
	}
	return o.Disabled, true
}

// HasDisabled returns a boolean if a field has been set.
func (o *PostPeople201Response) HasDisabled() bool {
	if o != nil && !IsNil(o.Disabled) {
		return true
	}

	return false
}

// SetDisabled gets a reference to the given bool and assigns it to the Disabled field.
func (o *PostPeople201Response) SetDisabled(v bool) {
	o.Disabled = &v
}

// GetDoNotTranslateLanguages returns the DoNotTranslateLanguages field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PostPeople201Response) GetDoNotTranslateLanguages() string {
	if o == nil || IsNil(o.DoNotTranslateLanguages.Get()) {
		var ret string
		return ret
	}
	return *o.DoNotTranslateLanguages.Get()
}

// GetDoNotTranslateLanguagesOk returns a tuple with the DoNotTranslateLanguages field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PostPeople201Response) GetDoNotTranslateLanguagesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DoNotTranslateLanguages.Get(), o.DoNotTranslateLanguages.IsSet()
}

// HasDoNotTranslateLanguages returns a boolean if a field has been set.
func (o *PostPeople201Response) HasDoNotTranslateLanguages() bool {
	if o != nil && o.DoNotTranslateLanguages.IsSet() {
		return true
	}

	return false
}

// SetDoNotTranslateLanguages gets a reference to the given NullableString and assigns it to the DoNotTranslateLanguages field.
func (o *PostPeople201Response) SetDoNotTranslateLanguages(v string) {
	o.DoNotTranslateLanguages.Set(&v)
}

// SetDoNotTranslateLanguagesNil sets the value for DoNotTranslateLanguages to be an explicit nil
func (o *PostPeople201Response) SetDoNotTranslateLanguagesNil() {
	o.DoNotTranslateLanguages.Set(nil)
}

// UnsetDoNotTranslateLanguages ensures that no value is present for DoNotTranslateLanguages, not even an explicit nil
func (o *PostPeople201Response) UnsetDoNotTranslateLanguages() {
	o.DoNotTranslateLanguages.Unset()
}

// GetEmployeeID returns the EmployeeID field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PostPeople201Response) GetEmployeeID() string {
	if o == nil || IsNil(o.EmployeeID.Get()) {
		var ret string
		return ret
	}
	return *o.EmployeeID.Get()
}

// GetEmployeeIDOk returns a tuple with the EmployeeID field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PostPeople201Response) GetEmployeeIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EmployeeID.Get(), o.EmployeeID.IsSet()
}

// HasEmployeeID returns a boolean if a field has been set.
func (o *PostPeople201Response) HasEmployeeID() bool {
	if o != nil && o.EmployeeID.IsSet() {
		return true
	}

	return false
}

// SetEmployeeID gets a reference to the given NullableString and assigns it to the EmployeeID field.
func (o *PostPeople201Response) SetEmployeeID(v string) {
	o.EmployeeID.Set(&v)
}

// SetEmployeeIDNil sets the value for EmployeeID to be an explicit nil
func (o *PostPeople201Response) SetEmployeeIDNil() {
	o.EmployeeID.Set(nil)
}

// UnsetEmployeeID ensures that no value is present for EmployeeID, not even an explicit nil
func (o *PostPeople201Response) UnsetEmployeeID() {
	o.EmployeeID.Unset()
}

// GetExcludeTeamNotifications returns the ExcludeTeamNotifications field value if set, zero value otherwise.
func (o *PostPeople201Response) GetExcludeTeamNotifications() bool {
	if o == nil || IsNil(o.ExcludeTeamNotifications) {
		var ret bool
		return ret
	}
	return *o.ExcludeTeamNotifications
}

// GetExcludeTeamNotificationsOk returns a tuple with the ExcludeTeamNotifications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostPeople201Response) GetExcludeTeamNotificationsOk() (*bool, bool) {
	if o == nil || IsNil(o.ExcludeTeamNotifications) {
		return nil, false
	}
	return o.ExcludeTeamNotifications, true
}

// HasExcludeTeamNotifications returns a boolean if a field has been set.
func (o *PostPeople201Response) HasExcludeTeamNotifications() bool {
	if o != nil && !IsNil(o.ExcludeTeamNotifications) {
		return true
	}

	return false
}

// SetExcludeTeamNotifications gets a reference to the given bool and assigns it to the ExcludeTeamNotifications field.
func (o *PostPeople201Response) SetExcludeTeamNotifications(v bool) {
	o.ExcludeTeamNotifications = &v
}

// GetFormats returns the Formats field value if set, zero value otherwise.
func (o *PostPeople201Response) GetFormats() PostPeople201ResponseFormats {
	if o == nil || IsNil(o.Formats) {
		var ret PostPeople201ResponseFormats
		return ret
	}
	return *o.Formats
}

// GetFormatsOk returns a tuple with the Formats field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostPeople201Response) GetFormatsOk() (*PostPeople201ResponseFormats, bool) {
	if o == nil || IsNil(o.Formats) {
		return nil, false
	}
	return o.Formats, true
}

// HasFormats returns a boolean if a field has been set.
func (o *PostPeople201Response) HasFormats() bool {
	if o != nil && !IsNil(o.Formats) {
		return true
	}

	return false
}

// SetFormats gets a reference to the given PostPeople201ResponseFormats and assigns it to the Formats field.
func (o *PostPeople201Response) SetFormats(v PostPeople201ResponseFormats) {
	o.Formats = &v
}

// GetGuest returns the Guest field value if set, zero value otherwise.
func (o *PostPeople201Response) GetGuest() bool {
	if o == nil || IsNil(o.Guest) {
		var ret bool
		return ret
	}
	return *o.Guest
}

// GetGuestOk returns a tuple with the Guest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostPeople201Response) GetGuestOk() (*bool, bool) {
	if o == nil || IsNil(o.Guest) {
		return nil, false
	}
	return o.Guest, true
}

// HasGuest returns a boolean if a field has been set.
func (o *PostPeople201Response) HasGuest() bool {
	if o != nil && !IsNil(o.Guest) {
		return true
	}

	return false
}

// SetGuest gets a reference to the given bool and assigns it to the Guest field.
func (o *PostPeople201Response) SetGuest(v bool) {
	o.Guest = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PostPeople201Response) GetId() float32 {
	if o == nil || IsNil(o.Id) {
		var ret float32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostPeople201Response) GetIdOk() (*float32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PostPeople201Response) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given float32 and assigns it to the Id field.
func (o *PostPeople201Response) SetId(v float32) {
	o.Id = &v
}

// GetInformation returns the Information field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PostPeople201Response) GetInformation() string {
	if o == nil || IsNil(o.Information.Get()) {
		var ret string
		return ret
	}
	return *o.Information.Get()
}

// GetInformationOk returns a tuple with the Information field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PostPeople201Response) GetInformationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Information.Get(), o.Information.IsSet()
}

// HasInformation returns a boolean if a field has been set.
func (o *PostPeople201Response) HasInformation() bool {
	if o != nil && o.Information.IsSet() {
		return true
	}

	return false
}

// SetInformation gets a reference to the given NullableString and assigns it to the Information field.
func (o *PostPeople201Response) SetInformation(v string) {
	o.Information.Set(&v)
}

// SetInformationNil sets the value for Information to be an explicit nil
func (o *PostPeople201Response) SetInformationNil() {
	o.Information.Set(nil)
}

// UnsetInformation ensures that no value is present for Information, not even an explicit nil
func (o *PostPeople201Response) UnsetInformation() {
	o.Information.Unset()
}

// GetJobTitle returns the JobTitle field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PostPeople201Response) GetJobTitle() string {
	if o == nil || IsNil(o.JobTitle.Get()) {
		var ret string
		return ret
	}
	return *o.JobTitle.Get()
}

// GetJobTitleOk returns a tuple with the JobTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PostPeople201Response) GetJobTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.JobTitle.Get(), o.JobTitle.IsSet()
}

// HasJobTitle returns a boolean if a field has been set.
func (o *PostPeople201Response) HasJobTitle() bool {
	if o != nil && o.JobTitle.IsSet() {
		return true
	}

	return false
}

// SetJobTitle gets a reference to the given NullableString and assigns it to the JobTitle field.
func (o *PostPeople201Response) SetJobTitle(v string) {
	o.JobTitle.Set(&v)
}

// SetJobTitleNil sets the value for JobTitle to be an explicit nil
func (o *PostPeople201Response) SetJobTitleNil() {
	o.JobTitle.Set(nil)
}

// UnsetJobTitle ensures that no value is present for JobTitle, not even an explicit nil
func (o *PostPeople201Response) UnsetJobTitle() {
	o.JobTitle.Unset()
}

// GetLocale returns the Locale field value if set, zero value otherwise.
func (o *PostPeople201Response) GetLocale() string {
	if o == nil || IsNil(o.Locale) {
		var ret string
		return ret
	}
	return *o.Locale
}

// GetLocaleOk returns a tuple with the Locale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostPeople201Response) GetLocaleOk() (*string, bool) {
	if o == nil || IsNil(o.Locale) {
		return nil, false
	}
	return o.Locale, true
}

// HasLocale returns a boolean if a field has been set.
func (o *PostPeople201Response) HasLocale() bool {
	if o != nil && !IsNil(o.Locale) {
		return true
	}

	return false
}

// SetLocale gets a reference to the given string and assigns it to the Locale field.
func (o *PostPeople201Response) SetLocale(v string) {
	o.Locale = &v
}

// GetLocation returns the Location field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PostPeople201Response) GetLocation() string {
	if o == nil || IsNil(o.Location.Get()) {
		var ret string
		return ret
	}
	return *o.Location.Get()
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PostPeople201Response) GetLocationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Location.Get(), o.Location.IsSet()
}

// HasLocation returns a boolean if a field has been set.
func (o *PostPeople201Response) HasLocation() bool {
	if o != nil && o.Location.IsSet() {
		return true
	}

	return false
}

// SetLocation gets a reference to the given NullableString and assigns it to the Location field.
func (o *PostPeople201Response) SetLocation(v string) {
	o.Location.Set(&v)
}

// SetLocationNil sets the value for Location to be an explicit nil
func (o *PostPeople201Response) SetLocationNil() {
	o.Location.Set(nil)
}

// UnsetLocation ensures that no value is present for Location, not even an explicit nil
func (o *PostPeople201Response) UnsetLocation() {
	o.Location.Unset()
}

// GetManager returns the Manager field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PostPeople201Response) GetManager() string {
	if o == nil || IsNil(o.Manager.Get()) {
		var ret string
		return ret
	}
	return *o.Manager.Get()
}

// GetManagerOk returns a tuple with the Manager field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PostPeople201Response) GetManagerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Manager.Get(), o.Manager.IsSet()
}

// HasManager returns a boolean if a field has been set.
func (o *PostPeople201Response) HasManager() bool {
	if o != nil && o.Manager.IsSet() {
		return true
	}

	return false
}

// SetManager gets a reference to the given NullableString and assigns it to the Manager field.
func (o *PostPeople201Response) SetManager(v string) {
	o.Manager.Set(&v)
}

// SetManagerNil sets the value for Manager to be an explicit nil
func (o *PostPeople201Response) SetManagerNil() {
	o.Manager.Set(nil)
}

// UnsetManager ensures that no value is present for Manager, not even an explicit nil
func (o *PostPeople201Response) UnsetManager() {
	o.Manager.Unset()
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PostPeople201Response) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostPeople201Response) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PostPeople201Response) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PostPeople201Response) SetName(v string) {
	o.Name = &v
}

// GetNodeID returns the NodeID field value if set, zero value otherwise.
func (o *PostPeople201Response) GetNodeID() string {
	if o == nil || IsNil(o.NodeID) {
		var ret string
		return ret
	}
	return *o.NodeID
}

// GetNodeIDOk returns a tuple with the NodeID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostPeople201Response) GetNodeIDOk() (*string, bool) {
	if o == nil || IsNil(o.NodeID) {
		return nil, false
	}
	return o.NodeID, true
}

// HasNodeID returns a boolean if a field has been set.
func (o *PostPeople201Response) HasNodeID() bool {
	if o != nil && !IsNil(o.NodeID) {
		return true
	}

	return false
}

// SetNodeID gets a reference to the given string and assigns it to the NodeID field.
func (o *PostPeople201Response) SetNodeID(v string) {
	o.NodeID = &v
}

// GetOauthPersonEnablement returns the OauthPersonEnablement field value if set, zero value otherwise.
func (o *PostPeople201Response) GetOauthPersonEnablement() bool {
	if o == nil || IsNil(o.OauthPersonEnablement) {
		var ret bool
		return ret
	}
	return *o.OauthPersonEnablement
}

// GetOauthPersonEnablementOk returns a tuple with the OauthPersonEnablement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostPeople201Response) GetOauthPersonEnablementOk() (*bool, bool) {
	if o == nil || IsNil(o.OauthPersonEnablement) {
		return nil, false
	}
	return o.OauthPersonEnablement, true
}

// HasOauthPersonEnablement returns a boolean if a field has been set.
func (o *PostPeople201Response) HasOauthPersonEnablement() bool {
	if o != nil && !IsNil(o.OauthPersonEnablement) {
		return true
	}

	return false
}

// SetOauthPersonEnablement gets a reference to the given bool and assigns it to the OauthPersonEnablement field.
func (o *PostPeople201Response) SetOauthPersonEnablement(v bool) {
	o.OauthPersonEnablement = &v
}

// GetOrganization returns the Organization field value if set, zero value otherwise.
func (o *PostPeople201Response) GetOrganization() GetRequestsId200ResponseCreatedBy {
	if o == nil || IsNil(o.Organization) {
		var ret GetRequestsId200ResponseCreatedBy
		return ret
	}
	return *o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostPeople201Response) GetOrganizationOk() (*GetRequestsId200ResponseCreatedBy, bool) {
	if o == nil || IsNil(o.Organization) {
		return nil, false
	}
	return o.Organization, true
}

// HasOrganization returns a boolean if a field has been set.
func (o *PostPeople201Response) HasOrganization() bool {
	if o != nil && !IsNil(o.Organization) {
		return true
	}

	return false
}

// SetOrganization gets a reference to the given GetRequestsId200ResponseCreatedBy and assigns it to the Organization field.
func (o *PostPeople201Response) SetOrganization(v GetRequestsId200ResponseCreatedBy) {
	o.Organization = &v
}

// GetPictureUri returns the PictureUri field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PostPeople201Response) GetPictureUri() string {
	if o == nil || IsNil(o.PictureUri.Get()) {
		var ret string
		return ret
	}
	return *o.PictureUri.Get()
}

// GetPictureUriOk returns a tuple with the PictureUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PostPeople201Response) GetPictureUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PictureUri.Get(), o.PictureUri.IsSet()
}

// HasPictureUri returns a boolean if a field has been set.
func (o *PostPeople201Response) HasPictureUri() bool {
	if o != nil && o.PictureUri.IsSet() {
		return true
	}

	return false
}

// SetPictureUri gets a reference to the given NullableString and assigns it to the PictureUri field.
func (o *PostPeople201Response) SetPictureUri(v string) {
	o.PictureUri.Set(&v)
}

// SetPictureUriNil sets the value for PictureUri to be an explicit nil
func (o *PostPeople201Response) SetPictureUriNil() {
	o.PictureUri.Set(nil)
}

// UnsetPictureUri ensures that no value is present for PictureUri, not even an explicit nil
func (o *PostPeople201Response) UnsetPictureUri() {
	o.PictureUri.Unset()
}

// GetPlayPrivateChatSound returns the PlayPrivateChatSound field value if set, zero value otherwise.
func (o *PostPeople201Response) GetPlayPrivateChatSound() string {
	if o == nil || IsNil(o.PlayPrivateChatSound) {
		var ret string
		return ret
	}
	return *o.PlayPrivateChatSound
}

// GetPlayPrivateChatSoundOk returns a tuple with the PlayPrivateChatSound field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostPeople201Response) GetPlayPrivateChatSoundOk() (*string, bool) {
	if o == nil || IsNil(o.PlayPrivateChatSound) {
		return nil, false
	}
	return o.PlayPrivateChatSound, true
}

// HasPlayPrivateChatSound returns a boolean if a field has been set.
func (o *PostPeople201Response) HasPlayPrivateChatSound() bool {
	if o != nil && !IsNil(o.PlayPrivateChatSound) {
		return true
	}

	return false
}

// SetPlayPrivateChatSound gets a reference to the given string and assigns it to the PlayPrivateChatSound field.
func (o *PostPeople201Response) SetPlayPrivateChatSound(v string) {
	o.PlayPrivateChatSound = &v
}

// GetPlaySupportChatSound returns the PlaySupportChatSound field value if set, zero value otherwise.
func (o *PostPeople201Response) GetPlaySupportChatSound() string {
	if o == nil || IsNil(o.PlaySupportChatSound) {
		var ret string
		return ret
	}
	return *o.PlaySupportChatSound
}

// GetPlaySupportChatSoundOk returns a tuple with the PlaySupportChatSound field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostPeople201Response) GetPlaySupportChatSoundOk() (*string, bool) {
	if o == nil || IsNil(o.PlaySupportChatSound) {
		return nil, false
	}
	return o.PlaySupportChatSound, true
}

// HasPlaySupportChatSound returns a boolean if a field has been set.
func (o *PostPeople201Response) HasPlaySupportChatSound() bool {
	if o != nil && !IsNil(o.PlaySupportChatSound) {
		return true
	}

	return false
}

// SetPlaySupportChatSound gets a reference to the given string and assigns it to the PlaySupportChatSound field.
func (o *PostPeople201Response) SetPlaySupportChatSound(v string) {
	o.PlaySupportChatSound = &v
}

// GetPrimaryEmail returns the PrimaryEmail field value if set, zero value otherwise.
func (o *PostPeople201Response) GetPrimaryEmail() string {
	if o == nil || IsNil(o.PrimaryEmail) {
		var ret string
		return ret
	}
	return *o.PrimaryEmail
}

// GetPrimaryEmailOk returns a tuple with the PrimaryEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostPeople201Response) GetPrimaryEmailOk() (*string, bool) {
	if o == nil || IsNil(o.PrimaryEmail) {
		return nil, false
	}
	return o.PrimaryEmail, true
}

// HasPrimaryEmail returns a boolean if a field has been set.
func (o *PostPeople201Response) HasPrimaryEmail() bool {
	if o != nil && !IsNil(o.PrimaryEmail) {
		return true
	}

	return false
}

// SetPrimaryEmail gets a reference to the given string and assigns it to the PrimaryEmail field.
func (o *PostPeople201Response) SetPrimaryEmail(v string) {
	o.PrimaryEmail = &v
}

// GetSendEmailNotifications returns the SendEmailNotifications field value if set, zero value otherwise.
func (o *PostPeople201Response) GetSendEmailNotifications() string {
	if o == nil || IsNil(o.SendEmailNotifications) {
		var ret string
		return ret
	}
	return *o.SendEmailNotifications
}

// GetSendEmailNotificationsOk returns a tuple with the SendEmailNotifications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostPeople201Response) GetSendEmailNotificationsOk() (*string, bool) {
	if o == nil || IsNil(o.SendEmailNotifications) {
		return nil, false
	}
	return o.SendEmailNotifications, true
}

// HasSendEmailNotifications returns a boolean if a field has been set.
func (o *PostPeople201Response) HasSendEmailNotifications() bool {
	if o != nil && !IsNil(o.SendEmailNotifications) {
		return true
	}

	return false
}

// SetSendEmailNotifications gets a reference to the given string and assigns it to the SendEmailNotifications field.
func (o *PostPeople201Response) SetSendEmailNotifications(v string) {
	o.SendEmailNotifications = &v
}

// GetShowNotificationPopup returns the ShowNotificationPopup field value if set, zero value otherwise.
func (o *PostPeople201Response) GetShowNotificationPopup() string {
	if o == nil || IsNil(o.ShowNotificationPopup) {
		var ret string
		return ret
	}
	return *o.ShowNotificationPopup
}

// GetShowNotificationPopupOk returns a tuple with the ShowNotificationPopup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostPeople201Response) GetShowNotificationPopupOk() (*string, bool) {
	if o == nil || IsNil(o.ShowNotificationPopup) {
		return nil, false
	}
	return o.ShowNotificationPopup, true
}

// HasShowNotificationPopup returns a boolean if a field has been set.
func (o *PostPeople201Response) HasShowNotificationPopup() bool {
	if o != nil && !IsNil(o.ShowNotificationPopup) {
		return true
	}

	return false
}

// SetShowNotificationPopup gets a reference to the given string and assigns it to the ShowNotificationPopup field.
func (o *PostPeople201Response) SetShowNotificationPopup(v string) {
	o.ShowNotificationPopup = &v
}

// GetShowPrivateChatPopup returns the ShowPrivateChatPopup field value if set, zero value otherwise.
func (o *PostPeople201Response) GetShowPrivateChatPopup() string {
	if o == nil || IsNil(o.ShowPrivateChatPopup) {
		var ret string
		return ret
	}
	return *o.ShowPrivateChatPopup
}

// GetShowPrivateChatPopupOk returns a tuple with the ShowPrivateChatPopup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostPeople201Response) GetShowPrivateChatPopupOk() (*string, bool) {
	if o == nil || IsNil(o.ShowPrivateChatPopup) {
		return nil, false
	}
	return o.ShowPrivateChatPopup, true
}

// HasShowPrivateChatPopup returns a boolean if a field has been set.
func (o *PostPeople201Response) HasShowPrivateChatPopup() bool {
	if o != nil && !IsNil(o.ShowPrivateChatPopup) {
		return true
	}

	return false
}

// SetShowPrivateChatPopup gets a reference to the given string and assigns it to the ShowPrivateChatPopup field.
func (o *PostPeople201Response) SetShowPrivateChatPopup(v string) {
	o.ShowPrivateChatPopup = &v
}

// GetShowSupportChatPopup returns the ShowSupportChatPopup field value if set, zero value otherwise.
func (o *PostPeople201Response) GetShowSupportChatPopup() string {
	if o == nil || IsNil(o.ShowSupportChatPopup) {
		var ret string
		return ret
	}
	return *o.ShowSupportChatPopup
}

// GetShowSupportChatPopupOk returns a tuple with the ShowSupportChatPopup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostPeople201Response) GetShowSupportChatPopupOk() (*string, bool) {
	if o == nil || IsNil(o.ShowSupportChatPopup) {
		return nil, false
	}
	return o.ShowSupportChatPopup, true
}

// HasShowSupportChatPopup returns a boolean if a field has been set.
func (o *PostPeople201Response) HasShowSupportChatPopup() bool {
	if o != nil && !IsNil(o.ShowSupportChatPopup) {
		return true
	}

	return false
}

// SetShowSupportChatPopup gets a reference to the given string and assigns it to the ShowSupportChatPopup field.
func (o *PostPeople201Response) SetShowSupportChatPopup(v string) {
	o.ShowSupportChatPopup = &v
}

// GetSite returns the Site field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PostPeople201Response) GetSite() string {
	if o == nil || IsNil(o.Site.Get()) {
		var ret string
		return ret
	}
	return *o.Site.Get()
}

// GetSiteOk returns a tuple with the Site field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PostPeople201Response) GetSiteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Site.Get(), o.Site.IsSet()
}

// HasSite returns a boolean if a field has been set.
func (o *PostPeople201Response) HasSite() bool {
	if o != nil && o.Site.IsSet() {
		return true
	}

	return false
}

// SetSite gets a reference to the given NullableString and assigns it to the Site field.
func (o *PostPeople201Response) SetSite(v string) {
	o.Site.Set(&v)
}

// SetSiteNil sets the value for Site to be an explicit nil
func (o *PostPeople201Response) SetSiteNil() {
	o.Site.Set(nil)
}

// UnsetSite ensures that no value is present for Site, not even an explicit nil
func (o *PostPeople201Response) UnsetSite() {
	o.Site.Unset()
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *PostPeople201Response) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostPeople201Response) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *PostPeople201Response) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *PostPeople201Response) SetSource(v string) {
	o.Source = &v
}

// GetSourceID returns the SourceID field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PostPeople201Response) GetSourceID() string {
	if o == nil || IsNil(o.SourceID.Get()) {
		var ret string
		return ret
	}
	return *o.SourceID.Get()
}

// GetSourceIDOk returns a tuple with the SourceID field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PostPeople201Response) GetSourceIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SourceID.Get(), o.SourceID.IsSet()
}

// HasSourceID returns a boolean if a field has been set.
func (o *PostPeople201Response) HasSourceID() bool {
	if o != nil && o.SourceID.IsSet() {
		return true
	}

	return false
}

// SetSourceID gets a reference to the given NullableString and assigns it to the SourceID field.
func (o *PostPeople201Response) SetSourceID(v string) {
	o.SourceID.Set(&v)
}

// SetSourceIDNil sets the value for SourceID to be an explicit nil
func (o *PostPeople201Response) SetSourceIDNil() {
	o.SourceID.Set(nil)
}

// UnsetSourceID ensures that no value is present for SourceID, not even an explicit nil
func (o *PostPeople201Response) UnsetSourceID() {
	o.SourceID.Unset()
}

// GetSupportID returns the SupportID field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PostPeople201Response) GetSupportID() string {
	if o == nil || IsNil(o.SupportID.Get()) {
		var ret string
		return ret
	}
	return *o.SupportID.Get()
}

// GetSupportIDOk returns a tuple with the SupportID field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PostPeople201Response) GetSupportIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SupportID.Get(), o.SupportID.IsSet()
}

// HasSupportID returns a boolean if a field has been set.
func (o *PostPeople201Response) HasSupportID() bool {
	if o != nil && o.SupportID.IsSet() {
		return true
	}

	return false
}

// SetSupportID gets a reference to the given NullableString and assigns it to the SupportID field.
func (o *PostPeople201Response) SetSupportID(v string) {
	o.SupportID.Set(&v)
}

// SetSupportIDNil sets the value for SupportID to be an explicit nil
func (o *PostPeople201Response) SetSupportIDNil() {
	o.SupportID.Set(nil)
}

// UnsetSupportID ensures that no value is present for SupportID, not even an explicit nil
func (o *PostPeople201Response) UnsetSupportID() {
	o.SupportID.Unset()
}

// GetTimeFormat24h returns the TimeFormat24h field value if set, zero value otherwise.
func (o *PostPeople201Response) GetTimeFormat24h() bool {
	if o == nil || IsNil(o.TimeFormat24h) {
		var ret bool
		return ret
	}
	return *o.TimeFormat24h
}

// GetTimeFormat24hOk returns a tuple with the TimeFormat24h field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostPeople201Response) GetTimeFormat24hOk() (*bool, bool) {
	if o == nil || IsNil(o.TimeFormat24h) {
		return nil, false
	}
	return o.TimeFormat24h, true
}

// HasTimeFormat24h returns a boolean if a field has been set.
func (o *PostPeople201Response) HasTimeFormat24h() bool {
	if o != nil && !IsNil(o.TimeFormat24h) {
		return true
	}

	return false
}

// SetTimeFormat24h gets a reference to the given bool and assigns it to the TimeFormat24h field.
func (o *PostPeople201Response) SetTimeFormat24h(v bool) {
	o.TimeFormat24h = &v
}

// GetTimeZone returns the TimeZone field value if set, zero value otherwise.
func (o *PostPeople201Response) GetTimeZone() string {
	if o == nil || IsNil(o.TimeZone) {
		var ret string
		return ret
	}
	return *o.TimeZone
}

// GetTimeZoneOk returns a tuple with the TimeZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostPeople201Response) GetTimeZoneOk() (*string, bool) {
	if o == nil || IsNil(o.TimeZone) {
		return nil, false
	}
	return o.TimeZone, true
}

// HasTimeZone returns a boolean if a field has been set.
func (o *PostPeople201Response) HasTimeZone() bool {
	if o != nil && !IsNil(o.TimeZone) {
		return true
	}

	return false
}

// SetTimeZone gets a reference to the given string and assigns it to the TimeZone field.
func (o *PostPeople201Response) SetTimeZone(v string) {
	o.TimeZone = &v
}

// GetUiExtension returns the UiExtension field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PostPeople201Response) GetUiExtension() string {
	if o == nil || IsNil(o.UiExtension.Get()) {
		var ret string
		return ret
	}
	return *o.UiExtension.Get()
}

// GetUiExtensionOk returns a tuple with the UiExtension field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PostPeople201Response) GetUiExtensionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UiExtension.Get(), o.UiExtension.IsSet()
}

// HasUiExtension returns a boolean if a field has been set.
func (o *PostPeople201Response) HasUiExtension() bool {
	if o != nil && o.UiExtension.IsSet() {
		return true
	}

	return false
}

// SetUiExtension gets a reference to the given NullableString and assigns it to the UiExtension field.
func (o *PostPeople201Response) SetUiExtension(v string) {
	o.UiExtension.Set(&v)
}

// SetUiExtensionNil sets the value for UiExtension to be an explicit nil
func (o *PostPeople201Response) SetUiExtensionNil() {
	o.UiExtension.Set(nil)
}

// UnsetUiExtension ensures that no value is present for UiExtension, not even an explicit nil
func (o *PostPeople201Response) UnsetUiExtension() {
	o.UiExtension.Unset()
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *PostPeople201Response) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostPeople201Response) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *PostPeople201Response) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *PostPeople201Response) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetVip returns the Vip field value if set, zero value otherwise.
func (o *PostPeople201Response) GetVip() bool {
	if o == nil || IsNil(o.Vip) {
		var ret bool
		return ret
	}
	return *o.Vip
}

// GetVipOk returns a tuple with the Vip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostPeople201Response) GetVipOk() (*bool, bool) {
	if o == nil || IsNil(o.Vip) {
		return nil, false
	}
	return o.Vip, true
}

// HasVip returns a boolean if a field has been set.
func (o *PostPeople201Response) HasVip() bool {
	if o != nil && !IsNil(o.Vip) {
		return true
	}

	return false
}

// SetVip gets a reference to the given bool and assigns it to the Vip field.
func (o *PostPeople201Response) SetVip(v bool) {
	o.Vip = &v
}

// GetWorkHours returns the WorkHours field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PostPeople201Response) GetWorkHours() string {
	if o == nil || IsNil(o.WorkHours.Get()) {
		var ret string
		return ret
	}
	return *o.WorkHours.Get()
}

// GetWorkHoursOk returns a tuple with the WorkHours field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PostPeople201Response) GetWorkHoursOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WorkHours.Get(), o.WorkHours.IsSet()
}

// HasWorkHours returns a boolean if a field has been set.
func (o *PostPeople201Response) HasWorkHours() bool {
	if o != nil && o.WorkHours.IsSet() {
		return true
	}

	return false
}

// SetWorkHours gets a reference to the given NullableString and assigns it to the WorkHours field.
func (o *PostPeople201Response) SetWorkHours(v string) {
	o.WorkHours.Set(&v)
}

// SetWorkHoursNil sets the value for WorkHours to be an explicit nil
func (o *PostPeople201Response) SetWorkHoursNil() {
	o.WorkHours.Set(nil)
}

// UnsetWorkHours ensures that no value is present for WorkHours, not even an explicit nil
func (o *PostPeople201Response) UnsetWorkHours() {
	o.WorkHours.Unset()
}

func (o PostPeople201Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostPeople201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Account) {
		toSerialize["account"] = o.Account
	}
	if !IsNil(o.Addresses) {
		toSerialize["addresses"] = o.Addresses
	}
	if !IsNil(o.Attachments) {
		toSerialize["attachments"] = o.Attachments
	}
	if o.AuthenticationID.IsSet() {
		toSerialize["authenticationID"] = o.AuthenticationID.Get()
	}
	if !IsNil(o.AutoTranslation) {
		toSerialize["auto_translation"] = o.AutoTranslation
	}
	if !IsNil(o.ColorMode) {
		toSerialize["color_mode"] = o.ColorMode
	}
	if !IsNil(o.Contacts) {
		toSerialize["contacts"] = o.Contacts
	}
	if o.CostPerHour.IsSet() {
		toSerialize["cost_per_hour"] = o.CostPerHour.Get()
	}
	if o.CostPerHourCurrency.IsSet() {
		toSerialize["cost_per_hour_currency"] = o.CostPerHourCurrency.Get()
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if o.CustomFields.IsSet() {
		toSerialize["custom_fields"] = o.CustomFields.Get()
	}
	if !IsNil(o.Disabled) {
		toSerialize["disabled"] = o.Disabled
	}
	if o.DoNotTranslateLanguages.IsSet() {
		toSerialize["do_not_translate_languages"] = o.DoNotTranslateLanguages.Get()
	}
	if o.EmployeeID.IsSet() {
		toSerialize["employeeID"] = o.EmployeeID.Get()
	}
	if !IsNil(o.ExcludeTeamNotifications) {
		toSerialize["exclude_team_notifications"] = o.ExcludeTeamNotifications
	}
	if !IsNil(o.Formats) {
		toSerialize["formats"] = o.Formats
	}
	if !IsNil(o.Guest) {
		toSerialize["guest"] = o.Guest
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if o.Information.IsSet() {
		toSerialize["information"] = o.Information.Get()
	}
	if o.JobTitle.IsSet() {
		toSerialize["job_title"] = o.JobTitle.Get()
	}
	if !IsNil(o.Locale) {
		toSerialize["locale"] = o.Locale
	}
	if o.Location.IsSet() {
		toSerialize["location"] = o.Location.Get()
	}
	if o.Manager.IsSet() {
		toSerialize["manager"] = o.Manager.Get()
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.NodeID) {
		toSerialize["nodeID"] = o.NodeID
	}
	if !IsNil(o.OauthPersonEnablement) {
		toSerialize["oauth_person_enablement"] = o.OauthPersonEnablement
	}
	if !IsNil(o.Organization) {
		toSerialize["organization"] = o.Organization
	}
	if o.PictureUri.IsSet() {
		toSerialize["picture_uri"] = o.PictureUri.Get()
	}
	if !IsNil(o.PlayPrivateChatSound) {
		toSerialize["play_private_chat_sound"] = o.PlayPrivateChatSound
	}
	if !IsNil(o.PlaySupportChatSound) {
		toSerialize["play_support_chat_sound"] = o.PlaySupportChatSound
	}
	if !IsNil(o.PrimaryEmail) {
		toSerialize["primary_email"] = o.PrimaryEmail
	}
	if !IsNil(o.SendEmailNotifications) {
		toSerialize["send_email_notifications"] = o.SendEmailNotifications
	}
	if !IsNil(o.ShowNotificationPopup) {
		toSerialize["show_notification_popup"] = o.ShowNotificationPopup
	}
	if !IsNil(o.ShowPrivateChatPopup) {
		toSerialize["show_private_chat_popup"] = o.ShowPrivateChatPopup
	}
	if !IsNil(o.ShowSupportChatPopup) {
		toSerialize["show_support_chat_popup"] = o.ShowSupportChatPopup
	}
	if o.Site.IsSet() {
		toSerialize["site"] = o.Site.Get()
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if o.SourceID.IsSet() {
		toSerialize["sourceID"] = o.SourceID.Get()
	}
	if o.SupportID.IsSet() {
		toSerialize["supportID"] = o.SupportID.Get()
	}
	if !IsNil(o.TimeFormat24h) {
		toSerialize["time_format_24h"] = o.TimeFormat24h
	}
	if !IsNil(o.TimeZone) {
		toSerialize["time_zone"] = o.TimeZone
	}
	if o.UiExtension.IsSet() {
		toSerialize["ui_extension"] = o.UiExtension.Get()
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.Vip) {
		toSerialize["vip"] = o.Vip
	}
	if o.WorkHours.IsSet() {
		toSerialize["work_hours"] = o.WorkHours.Get()
	}
	return toSerialize, nil
}

type NullablePostPeople201Response struct {
	value *PostPeople201Response
	isSet bool
}

func (v NullablePostPeople201Response) Get() *PostPeople201Response {
	return v.value
}

func (v *NullablePostPeople201Response) Set(val *PostPeople201Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePostPeople201Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePostPeople201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostPeople201Response(val *PostPeople201Response) *NullablePostPeople201Response {
	return &NullablePostPeople201Response{value: val, isSet: true}
}

func (v NullablePostPeople201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostPeople201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
