/*
Xurrent REST API

Xurrent REST API. Global conventions (injected on collection GETs): pagination (`per_page`, `search_after`, `search_before`), field selection (`fields`), ordering (`sort`), predefined state (`state`), and `X-Xurrent-Language`. Resource-specific filters use additional query parameters per https://developer.xurrent.com/v1/general/filtering/ — use `collection_query.go` helpers or append encoded query pairs when filters are not modeled as named parameters.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xurrent

import (
	"encoding/json"
)

// checks if the GetRequestsIdCis200ResponseInnerService type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRequestsIdCis200ResponseInnerService{}

// GetRequestsIdCis200ResponseInnerService struct for GetRequestsIdCis200ResponseInnerService
type GetRequestsIdCis200ResponseInnerService struct {
	Account       *GetRequestsId200ResponseAccount   `json:"account,omitempty"`
	Id            *float32                           `json:"id,omitempty"`
	LocalizedName *string                            `json:"localized_name,omitempty"`
	Name          *string                            `json:"name,omitempty"`
	NodeID        *string                            `json:"nodeID,omitempty"`
	Provider      *GetRequestsId200ResponseCreatedBy `json:"provider,omitempty"`
}

// NewGetRequestsIdCis200ResponseInnerService instantiates a new GetRequestsIdCis200ResponseInnerService object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRequestsIdCis200ResponseInnerService() *GetRequestsIdCis200ResponseInnerService {
	this := GetRequestsIdCis200ResponseInnerService{}
	return &this
}

// NewGetRequestsIdCis200ResponseInnerServiceWithDefaults instantiates a new GetRequestsIdCis200ResponseInnerService object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRequestsIdCis200ResponseInnerServiceWithDefaults() *GetRequestsIdCis200ResponseInnerService {
	this := GetRequestsIdCis200ResponseInnerService{}
	return &this
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *GetRequestsIdCis200ResponseInnerService) GetAccount() GetRequestsId200ResponseAccount {
	if o == nil || IsNil(o.Account) {
		var ret GetRequestsId200ResponseAccount
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRequestsIdCis200ResponseInnerService) GetAccountOk() (*GetRequestsId200ResponseAccount, bool) {
	if o == nil || IsNil(o.Account) {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *GetRequestsIdCis200ResponseInnerService) HasAccount() bool {
	if o != nil && !IsNil(o.Account) {
		return true
	}

	return false
}

// SetAccount gets a reference to the given GetRequestsId200ResponseAccount and assigns it to the Account field.
func (o *GetRequestsIdCis200ResponseInnerService) SetAccount(v GetRequestsId200ResponseAccount) {
	o.Account = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetRequestsIdCis200ResponseInnerService) GetId() float32 {
	if o == nil || IsNil(o.Id) {
		var ret float32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRequestsIdCis200ResponseInnerService) GetIdOk() (*float32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetRequestsIdCis200ResponseInnerService) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given float32 and assigns it to the Id field.
func (o *GetRequestsIdCis200ResponseInnerService) SetId(v float32) {
	o.Id = &v
}

// GetLocalizedName returns the LocalizedName field value if set, zero value otherwise.
func (o *GetRequestsIdCis200ResponseInnerService) GetLocalizedName() string {
	if o == nil || IsNil(o.LocalizedName) {
		var ret string
		return ret
	}
	return *o.LocalizedName
}

// GetLocalizedNameOk returns a tuple with the LocalizedName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRequestsIdCis200ResponseInnerService) GetLocalizedNameOk() (*string, bool) {
	if o == nil || IsNil(o.LocalizedName) {
		return nil, false
	}
	return o.LocalizedName, true
}

// HasLocalizedName returns a boolean if a field has been set.
func (o *GetRequestsIdCis200ResponseInnerService) HasLocalizedName() bool {
	if o != nil && !IsNil(o.LocalizedName) {
		return true
	}

	return false
}

// SetLocalizedName gets a reference to the given string and assigns it to the LocalizedName field.
func (o *GetRequestsIdCis200ResponseInnerService) SetLocalizedName(v string) {
	o.LocalizedName = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetRequestsIdCis200ResponseInnerService) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRequestsIdCis200ResponseInnerService) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetRequestsIdCis200ResponseInnerService) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetRequestsIdCis200ResponseInnerService) SetName(v string) {
	o.Name = &v
}

// GetNodeID returns the NodeID field value if set, zero value otherwise.
func (o *GetRequestsIdCis200ResponseInnerService) GetNodeID() string {
	if o == nil || IsNil(o.NodeID) {
		var ret string
		return ret
	}
	return *o.NodeID
}

// GetNodeIDOk returns a tuple with the NodeID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRequestsIdCis200ResponseInnerService) GetNodeIDOk() (*string, bool) {
	if o == nil || IsNil(o.NodeID) {
		return nil, false
	}
	return o.NodeID, true
}

// HasNodeID returns a boolean if a field has been set.
func (o *GetRequestsIdCis200ResponseInnerService) HasNodeID() bool {
	if o != nil && !IsNil(o.NodeID) {
		return true
	}

	return false
}

// SetNodeID gets a reference to the given string and assigns it to the NodeID field.
func (o *GetRequestsIdCis200ResponseInnerService) SetNodeID(v string) {
	o.NodeID = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *GetRequestsIdCis200ResponseInnerService) GetProvider() GetRequestsId200ResponseCreatedBy {
	if o == nil || IsNil(o.Provider) {
		var ret GetRequestsId200ResponseCreatedBy
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRequestsIdCis200ResponseInnerService) GetProviderOk() (*GetRequestsId200ResponseCreatedBy, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *GetRequestsIdCis200ResponseInnerService) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given GetRequestsId200ResponseCreatedBy and assigns it to the Provider field.
func (o *GetRequestsIdCis200ResponseInnerService) SetProvider(v GetRequestsId200ResponseCreatedBy) {
	o.Provider = &v
}

func (o GetRequestsIdCis200ResponseInnerService) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRequestsIdCis200ResponseInnerService) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Account) {
		toSerialize["account"] = o.Account
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.LocalizedName) {
		toSerialize["localized_name"] = o.LocalizedName
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.NodeID) {
		toSerialize["nodeID"] = o.NodeID
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	return toSerialize, nil
}

type NullableGetRequestsIdCis200ResponseInnerService struct {
	value *GetRequestsIdCis200ResponseInnerService
	isSet bool
}

func (v NullableGetRequestsIdCis200ResponseInnerService) Get() *GetRequestsIdCis200ResponseInnerService {
	return v.value
}

func (v *NullableGetRequestsIdCis200ResponseInnerService) Set(val *GetRequestsIdCis200ResponseInnerService) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRequestsIdCis200ResponseInnerService) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRequestsIdCis200ResponseInnerService) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRequestsIdCis200ResponseInnerService(val *GetRequestsIdCis200ResponseInnerService) *NullableGetRequestsIdCis200ResponseInnerService {
	return &NullableGetRequestsIdCis200ResponseInnerService{value: val, isSet: true}
}

func (v NullableGetRequestsIdCis200ResponseInnerService) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRequestsIdCis200ResponseInnerService) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
